### ISSUE TITLE
Rework of the converters

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee-shepherd-converters#107]
Hi @Koenkk
Due to the large number of issues which are opened again and again with the same problems:

e.g. Do I have a new device, how can I integrate it ?
e.g. How can I edit the file xyz ?
e.g. Multiple Converter for other devices but somehow different.
etc.
etc.

I have considered to revise the current state of converter.

Therefore I thought about the following structure:

per device a separate file e.g. vendor_model_ownedefinition.js

content. the section for fromZ

the section for fromZigbee and toZigbee as well as the actual ``devices`` part
e.g.
```
{
        zigbeeModel: ['lumi.sensor_switch'],
        model: 'WXKG01LM',
        vendor: 'Xiaomi',
        description: 'MiJia wireless switch',
        supports: 'single, double, triple, quadruple, many, long, long_release click',
        fromZigbee: [fz.xiaomi_battery_3v, fz.WXKG01LM_click, fz.ignore_onoff_change, fz.ignore_basic_change],
        toZigbee: [],
    },
```

so we have an own exact assignment for the converters for each model.
The advantage: Dynamic editing per model as well as simple adding of own models (e.g. with HASSIO).

I can take over the revision, but I need your help regarding the exports and the associated processing.

Maybe you would be interested to do this with me soon ?

**Comment by Koenkk** [comment]
Yes, but I doubt of this would solve the problems. Most people have trouble finding the `devices.js` file, understanding it isn't a problem most of the times. We get a lot of PR's supporting new devices which are most of the time good.
