### ISSUE TITLE
Xiaomi Mija: Contact interval not supported

### ISSUE THREAD

**Issue by modmax** [Koenkk/zigbee-shepherd-converters#111]
With Pull request 108
(https://github.com/Koenkk/zigbee-shepherd-converters/commit/b98428b532a5fe9a3518eedd6cab5f655874c621)
there the xiaomi_contact_interval was introduced.

But this only works for Aqara sensors, not Mija sensors ...
So the change shopuld be rolled back ...
I will create a pull request fpr that ...

**Comment by Koenkk** [comment]
merged, thanks!
