### ISSUE TITLE
NodeJS 4.* support

### ISSUE THREAD

**Issue by kirovilya** [Koenkk/zigbee-shepherd-converters#145]
Hi, @Koenkk 
I do not know why, but in the published package (since version 5.0.0) there is a dependence by debug == 4.0.1
https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/npm-shrinkwrap.json#L215

But unfortunately, in this release `debug` has stopped supporting NodeJS 4.*
https://github.com/visionmedia/debug/releases/tag/4.0.0

This is very sad for my code, which still continues to support it.

Can we try to reduce the dependency package debug?

**Comment by Koenkk** [comment]
Yes no problem, which `debug` version do you require? Can you update `package.json`?

**Comment by kirovilya** [comment]
for example like this https://github.com/Koenkk/zigbee-shepherd/blob/master/package.json#L37
but here no 'debug' in package.json :)

**Comment by kirovilya** [comment]
thank you. all works
