### ISSUE TITLE
Xiaomi/Honeywell smoke detector modelID 'undefined'

### ISSUE THREAD

**Issue by KoumaMisna** [Koenkk/zigbee-shepherd-converters#261]
Hi!

Just got three Xiaomi smoke detectors and zigbee2mqtt says:
`zigbee2mqtt:warn 2019-2-3 12:02:16 Device with modelID 'undefined' is not supported.`

Still I get data from them:
`zigbee2mqtt:info 2019-2-3 15:31:55 MQTT publish: topic 'zigbee2mqtt/0x00158d0002527271', payload '{"battery":100,"voltage":3235,"linkquality":128}'`

Here is some info from the smokes:
`zigbee2mqtt:info 2019-2-3 12:02:16 MQTT publish: topic 'homeassistant/sensor/0x00158d0002527271/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/0x00158d0002527271","json_attributes_topic":"zigbee2mqtt/0x00158d0002527271","name":"0x00158d0002527271_battery","unique_id":"0x00158d0002527271_battery_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x00158d0002527271","name":"0x00158d0002527271","sw_version":"Zigbee2mqtt 1.1.0","model":"MiJia Honeywell smoke detector (JTYJ-GD-01LM/BW)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'`

**Comment by KoumaMisna** [comment]
Hi!

Here is the whole log. So I get data from 1 of 3 smoke detectors. They all came with the same order.

In state.json there is only the working one.

In configuration.yaml there are all three.

Here is the full log from today:

`2019-2-3 10:52:44 - info: Logging to directory: '/share/zigbee2mqtt/log/2019-02-03.10-52-44'
2019-2-3 10:53:06 - info: Starting zigbee2mqtt version 1.1.0 (commit #unknown)
2019-2-3 10:53:06 - info: Starting zigbee-shepherd
2019-2-3 10:53:10 - info: zigbee-shepherd started
2019-2-3 10:53:10 - info: Coordinator firmware version: '20181024'
2019-2-3 10:53:10 - info: Currently 0 devices are joined:
2019-2-3 10:53:10 - info: Zigbee: disabling joining new devices.
2019-2-3 10:53:10 - info: Connecting to MQTT server at mqtt://192.168.10.21:1883
2019-2-3 10:53:10 - info: zigbee-shepherd ready
2019-2-3 10:53:10 - info: Connected to MQTT server
2019-2-3 10:53:10 - info: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
2019-2-3 11:04:53 - info: Zigbee: allowing new devices to join.
2019-2-3 11:04:53 - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","permit_join":true}'
2019-2-3 11:06:25 - error: Cannot get the Node Descriptor of the Device: 0x00158d0002b09eaa (Error: Timed out after 10000 ms)
2019-2-3 11:06:48 - error: Cannot get the Node Descriptor of the Device: 0x00158d0002b09eaa (Error: Timed out after 10000 ms)
2019-2-3 11:07:08 - error: Cannot get the Node Descriptor of the Device: 0x00158d0002b09eaa (Error: Timed out after 10000 ms)
2019-2-3 11:08:06 - error: Cannot get the Node Descriptor of the Device: 0x00158d0002b09eaa (Error: Timed out after 10000 ms)
2019-2-3 11:08:26 - error: Cannot get the Node Descriptor of the Device: 0x00158d0002b09eaa (Error: Timed out after 10000 ms)
2019-2-3 12:01:41 - info: Zigbee: allowing new devices to join.
2019-2-3 12:01:41 - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","permit_join":true}'
2019-2-3 12:02:12 - info: New device with address 0x00158d0002527271 connected!
2019-2-3 12:02:12 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x00158d0002527271"}'
2019-2-3 12:02:12 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 12:02:12 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 12:02:12 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 12:02:12 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 12:02:16 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 12:02:16 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 12:02:16 - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002527271', payload '{"battery":100,"voltage":3055,"linkquality":126}'
2019-2-3 12:02:16 - info: MQTT publish: topic 'homeassistant/binary_sensor/0x00158d0002527271/smoke/config', payload '{"payload_on":true,"payload_off":false,"value_template":"{{ value_json.smoke }}","device_class":"smoke","state_topic":"zigbee2mqtt/0x00158d0002527271","json_attributes_topic":"zigbee2mqtt/0x00158d0002527271","name":"0x00158d0002527271_smoke","unique_id":"0x00158d0002527271_smoke_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x00158d0002527271","name":"0x00158d0002527271","sw_version":"Zigbee2mqtt 1.1.0","model":"MiJia Honeywell smoke detector (JTYJ-GD-01LM/BW)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
2019-2-3 12:02:16 - info: MQTT publish: topic 'homeassistant/sensor/0x00158d0002527271/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/0x00158d0002527271","json_attributes_topic":"zigbee2mqtt/0x00158d0002527271","name":"0x00158d0002527271_battery","unique_id":"0x00158d0002527271_battery_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x00158d0002527271","name":"0x00158d0002527271","sw_version":"Zigbee2mqtt 1.1.0","model":"MiJia Honeywell smoke detector (JTYJ-GD-01LM/BW)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
2019-2-3 12:03:02 - info: Device incoming...
2019-2-3 12:03:02 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
2019-2-3 12:11:42 - info: Zigbee: disabling joining new devices.
2019-2-3 12:11:42 - info: Zigbee: disabling joining new devices.
2019-2-3 12:11:42 - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","permit_join":false}'
2019-2-3 12:11:42 - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","permit_join":false}'
2019-2-3 12:48:01 - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002527271', payload '{"battery":100,"voltage":3235,"linkquality":126}'
2019-2-3 13:43:49 - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002527271', payload '{"battery":100,"voltage":3235,"linkquality":126}'
2019-2-3 14:40:07 - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002527271', payload '{"battery":100,"voltage":3235,"linkquality":126}'
2019-2-3 15:31:55 - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002527271', payload '{"battery":100,"voltage":3235,"linkquality":128}'
2019-2-3 15:50:36 - info: Zigbee: allowing new devices to join.
2019-2-3 15:50:36 - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","permit_join":true}'
2019-2-3 15:52:05 - error: Cannot get the Node Descriptor of the Device: 0x00158d0002ad4a82 (Error: Timed out after 10000 ms)
2019-2-3 15:52:26 - error: Cannot get the Node Descriptor of the Device: 0x00158d0002ad4a82 (Error: Timed out after 10000 ms)
2019-2-3 15:52:49 - warn: Message without device!
2019-2-3 15:53:04 - info: Connecting with device...
2019-2-3 15:53:04 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"connecting with device"}'
2019-2-3 15:53:05 - info: Connecting with device...
2019-2-3 15:53:05 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"connecting with device"}'
2019-2-3 15:53:06 - info: Connecting with device...
2019-2-3 15:53:06 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"connecting with device"}'
2019-2-3 15:53:07 - info: Connecting with device...
2019-2-3 15:53:07 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"connecting with device"}'
2019-2-3 15:53:07 - info: Connecting with device...
2019-2-3 15:53:07 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"connecting with device"}'
2019-2-3 15:53:08 - info: Connecting with device...
2019-2-3 15:53:08 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"connecting with device"}'
2019-2-3 15:53:09 - info: Connecting with device...
2019-2-3 15:53:09 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"connecting with device"}'
2019-2-3 15:53:09 - info: Device incoming...
2019-2-3 15:53:09 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
2019-2-3 15:53:09 - info: New device with address 0x00158d0002ad4a82 connected!
2019-2-3 15:53:09 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x00158d0002ad4a82"}'
2019-2-3 15:53:09 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 15:53:09 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 15:53:09 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 15:53:09 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 15:53:56 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 15:53:56 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 15:53:56 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 15:53:56 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 15:53:56 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 15:53:56 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 15:54:35 - info: Device incoming...
2019-2-3 15:54:35 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
2019-2-3 15:54:35 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 15:54:35 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 15:54:35 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 15:54:35 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 16:00:37 - info: Zigbee: disabling joining new devices.
2019-2-3 16:00:37 - info: Zigbee: disabling joining new devices.
2019-2-3 16:00:37 - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","permit_join":false}'
2019-2-3 16:00:37 - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","permit_join":false}'
2019-2-3 16:23:58 - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002527271', payload '{"battery":100,"voltage":3235,"linkquality":97}'
2019-2-3 16:27:46 - info: Zigbee: allowing new devices to join.
2019-2-3 16:27:46 - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","permit_join":true}'
2019-2-3 16:28:32 - info: New device with address 0x00158d0002b09eaa connected!
2019-2-3 16:28:32 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":"0x00158d0002b09eaa"}'
2019-2-3 16:28:32 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 16:28:32 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 16:28:32 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 16:28:32 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 16:29:08 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 16:29:08 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 16:29:08 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 16:29:08 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 16:29:08 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 16:29:08 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 16:29:48 - info: Device incoming...
2019-2-3 16:29:48 - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
2019-2-3 16:29:48 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 16:29:48 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 16:29:48 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 16:29:48 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 16:37:47 - info: Zigbee: disabling joining new devices.
2019-2-3 16:37:47 - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","permit_join":false}'
2019-2-3 16:37:47 - info: Zigbee: disabling joining new devices.
2019-2-3 16:37:47 - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"info","permit_join":false}'
2019-2-3 16:38:53 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 16:38:53 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 16:38:53 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 16:38:53 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 17:14:20 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 17:14:20 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 17:14:20 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 17:14:20 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 17:19:16 - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002527271', payload '{"battery":100,"voltage":3235,"linkquality":97}'
2019-2-3 17:37:26 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 17:37:26 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 17:37:26 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 17:37:26 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 18:10:23 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 18:10:23 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 18:18:19 - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002527271', payload '{"battery":100,"voltage":3235,"linkquality":97}'
2019-2-3 18:34:29 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 18:34:29 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 18:34:29 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 18:34:29 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 19:09:41 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 19:09:41 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 19:09:41 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 19:09:41 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 19:13:07 - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002527271', payload '{"battery":100,"voltage":3235,"linkquality":97}'
2019-2-3 19:30:02 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 19:30:02 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 19:30:02 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 19:30:02 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 20:00:13 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 20:00:13 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 20:00:13 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 20:00:13 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 20:06:10 - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002527271', payload '{"battery":100,"voltage":3235,"linkquality":97}'
2019-2-3 20:29:20 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 20:29:20 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 20:29:20 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 20:29:20 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 20:51:46 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 20:51:46 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 20:51:46 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 20:51:46 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 21:04:13 - info: MQTT publish: topic 'zigbee2mqtt/0x00158d0002527271', payload '{"battery":100,"voltage":3235,"linkquality":97}'
2019-2-3 21:21:23 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 21:21:23 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 21:21:23 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 21:21:23 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 21:43:49 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 21:43:49 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
2019-2-3 21:43:49 - warn: Device with modelID 'undefined' is not supported.
2019-2-3 21:43:49 - warn: Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html
`

**Comment by Koenkk** [comment]
The pairing procedure has not fully been completed.

- Stop zigbee2mqtt
- Remove all entries of `0x00158d0002b09eaa` from database.db
- Start zigbee2mqtt
- Repair by following https://koenkk.github.io/zigbee2mqtt/getting_started/pairing_devices.html#xiaomi

**Comment by KoumaMisna** [comment]
Hi!

I managed to corrupt the database but your advice helped!

I still don’t see battery voltage and signal strength in home assistant but I think that must be a problem with mqtt autodiscovery because zigbee2mqtt publishes the data to mosquitto.

**Comment by KoumaMisna** [comment]
Btw @Koenkk I didn't find any good instructions on how to pair the smoke detectors. I could write instructions but don't know how to upload them to the wiki. Can I send them to you and you could upload them?
