### ISSUE TITLE
FNB56-ZSW01LX2.0 - 3A Zigbee switch (2 gang)

### ISSUE THREAD

**Issue by mdn-united** [Koenkk/zigbee-shepherd-converters#278]
hi, 
I thought I could figure it out how to edit the device.js myself. But I failed.

I bought the 3A Zigbee 3.0 Smart Switch FNB56-ZSW01LX2.0 (https://3asmarthome.com/smart-switches)

Here is what I put in the devices.js:
```
   // 3A Zigbee 3.0 Smart Switch
   {
        zigbeeModel: ['FNB56-ZSW01LX2.0'],
        model: 'FNB56-ZSW01LX2.0',
        description:
                'Zigbee 3.0 switch 2 gang ',
        vendor: '3A',
        supports: 'on/off',
        fromZigbee: [fz.ignore_onoff_change, fz.generic_state],
        toZigbee: [tz.on_off],
   },
```

An here is what I got when I pressed one of the switches:
https://pastebin.com/nsAg4cqq
(282 lines - that's why I used pastebin)

@Koenkk can you help me with my devices.js ?

**Comment by Koenkk** [comment]
@mdn-united would you mind setting zigbee2mqtt up for this? I'm not comfortable with the logging of iobroker. Once it's supported you can of course use it with iobroker.

**Comment by mdn-united** [comment]
I tried to install zigbee2mqtt (https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html) on my raspberry but there is an error message:
`zigbee2mqtt:error 2019-2-13 21:30:50 Not connected to MQTT server!`
I tried to connect with a MQTT app from my computer to my raspberry and it didn't work either. 
I made no changes to the configuration.yaml, because I have the CC2531 stick and I don't know how to set a username and password.

So I guess, the answer of your question is: I wouldn't mind, but it's not working.

**Comment by mdn-united** [comment]
Ah! I figured it out! There was no MQTT Server. After I "sudo apt-get install mosquitto" the server I got a connection. Now I'm trying to connect my device.  (And maybe you should add that to the install manual. Beginners like would find it very helpful.)

**Comment by mdn-united** [comment]
hi @Koenkk 
I hope that you want the console output:
Switching off: No converter available for 'HGZB-42-UK' with cid 'genOnOff', type 'attReport' and data '{"cid":"genOnOff","data":{"onOff":0}}' 
Switching on: No converter available for 'HGZB-42-UK' with cid 'genOnOff', type 'attReport' and data '{"cid":"genOnOff","data":{"onOff":1}}'

**Comment by mdn-united** [comment]
I think I figured it out my self. 
This is what I have now in the devices.js
  ```
   {
        // 3A Zigbee 3.0 Smart Switch
        zigbeeModel: ['FNB56-ZSW01LX2.0'],
        model: 'HGZB-42-UK',
        vendor: '3A',
        description: 'Zigbee 3.0 Smart Switch 2 Gang ',
        supports: 'on and off',
        fromZigbee: [fz.WXKG01LM_click,fz.light_state],
        toZigbee: [],
    },
```
That seems to work very well. I now get messages like this:
```
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"ON","contact":true,"linkquality":110}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"OFF","contact":true,"linkquality":110}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"OFF","contact":true,"linkquality":110,"click":"long"}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"OFF","contact":true,"linkquality":99,"click":"long_release","duration":4766}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"ON","contact":true,"linkquality":110}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"OFF","contact":true,"linkquality":110}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"OFF","contact":true,"linkquality":113,"click":"long"}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"OFF","contact":true,"linkquality":99,"click":"long_release","duration":6668}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"ON","contact":true,"linkquality":110}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"OFF","contact":true,"linkquality":110}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"OFF","contact":true,"linkquality":110,"click":"long"}'
```

The next step is to try it in ioBroker.

**Comment by mdn-united** [comment]
unfortunately iobroker does not accept my changes to the devices.js.
That is what I put in the devices.js:
```
      // 3A Zigbee 3.0 Smart Switch

    {
       zigbeeModel: ['FNB56-ZSW01LX2.0'],
       model: 'HGZB-42-UK',
       vendor: '3A',
       description: 'Zigbee 3.0 Smart Switch 2 Gang ',
       supports: 'on and off',
       fromZigbee: [fz.WXKG01LM_click, fz.light_state],
       toZigbee: [],
    },
```
After several reboots, resets, re-joins I still get errors like this:

error | Unknown device model FNB56-ZSW01LX2.0 emit event devChange with data:{"cid":"genOnOff","data":{"onOff":1}}
error | Unknown device model FNB56-ZSW01LX2.0 emit event attReport with data:{"cid":"genOnOff","data":{"onOff":1}}
error | Unknown device model FNB56-ZSW01LX2.0 emit event devChange with data:{"cid":"genOnOff","data":{"onOff":0}}
error | Unknown device model FNB56-ZSW01LX2.0 emit event attReport with data:{"cid":"genOnOff","data":{"onOff":0}}

but I can send commands to the switch:
![grafik](https://user-images.githubusercontent.com/11157159/52748173-1c94ad00-2fe6-11e9-9471-c2be772d55f2.png)

**Comment by Koenkk** [comment]
The next step is to integrate it with zigbee-shepherd-converters, (ioboker comes after that).

But you probably cannot control both gangs yet.

Can you share your `data/database.db`?

**Comment by mdn-united** [comment]
here it is!
[database.db.txt](https://github.com/Koenkk/zigbee-shepherd-converters/files/2866135/database.db.txt)

**Comment by Koenkk** [comment]
I only see 1 endpoint for this device (1 gang). Do you have the original gateway? We need to find out how the second gang is controlled. http://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by mdn-united** [comment]
Well, I'm not an expert, but to me it looks like 2 devices in one case. 
```
{"id":3,"type":"Router","ieeeAddr":"0x00158d000258456b","nwkAddr":36720
{"id":2,"type":"Router","ieeeAddr":"0x00158d00025d7a9e","nwkAddr":58407
```
That is also what I see in ioBroker. There I see tow devices. It has even two identically looking chips in the device. So I guess every devices is controlled separately.

**Comment by ryanbeaton** [comment]
Just an note for @Koenkk the 3A and Nue gear is the same. Maybe @highground88 can assist?

**Comment by highground88** [comment]
@mdn-united  please see here for my exoerience so far: #https://github.com/Koenkk/zigbee2mqtt/issues/176
#https://github.com/Koenkk/zigbee-shepherd-converters/pull/242

@ryanbeaton Thanks Ryan, yes the "3A" and NUE switches are one in the same. But this is yet another model of the 2-gang switch - mine were FB56+ZSW1HKJ2.5 & FB56+ZSW1HKJ1.7.  So now we also have a "FNB56-ZSW01LX2.0" .....  I wonder what the differences both software and hardware might be.

Unfortunately I've been away with work and haven't been home to play any further for a few weeks..... but it looks like everyone is starting to get some partial success at least. It's a shame the supplier hasn't come to the party and helped like he has with Smart Things.

**Comment by highground88** [comment]
#177 also appears to be based on the same hardware but with a different branding ....

**Comment by Koenkk** [comment]
@mdn-united so can you control both gangs by sending over MQTT to `zigbee2mqtt/0x00158d000258456b/set` `ON` and `zigbee2mqtt/0x00158d00025d7a9e/set` `ON` and

**Comment by mdn-united** [comment]
@Koenkk 
> 
> 
> @mdn-united so can you control both gangs by sending over MQTT to `zigbee2mqtt/0x00158d000258456b/set` `ON` and `zigbee2mqtt/0x00158d00025d7a9e/set` `ON` and

I don't know how to do it. Just typing "zigbee2mqtt/0x00158d000258456b/set ON" didn't work. 
But if I simulate switching with ioBroker it works. If I want to change the other side of the switch I have to select another device. 
![grafik](https://user-images.githubusercontent.com/11157159/52846028-db48ee00-3108-11e9-9846-392c902eabd1.png)
![grafik](https://user-images.githubusercontent.com/11157159/52846054-ec91fa80-3108-11e9-9817-8566f0f662eb.png)
![grafik](https://user-images.githubusercontent.com/11157159/52846199-501c2800-3109-11e9-8354-d1d3aa44ce4a.png)

Here is a picture from the switch with the front removed. To me it looks like two devices in one case.
![20190215_101101](https://user-images.githubusercontent.com/11157159/52846575-3fb87d00-310a-11e9-8327-8aa3b39ef1f8.jpg)

btw: I don't know what a pull request is. I'm a Windows Server admin, not a developer. I've never worked with Github before. But I'm willing to do my part to make the Zigbee adapter compatible with various devices. This is my first device, so I need more help and instructions. Next time I will be able to give you the necessary information straightaway.

**Comment by highground88** [comment]
Wow okay that's definitely two seperate transmitters..... I've not seen that before and am kind of concerned for my own devices as to why they needed to do that?

Try connecting a free MQTT client (such as MQTT.fx) to your MQTT broker on your Home Assistant and send (publish) the string above that Koen suggested. You can also subscribe to channel Zigbee2Mqtt/# or just # to look at MQTT messages.



On Fri., 15 Feb. 2019, 7:18 pm mdn-united <notifications@github.com<mailto:notifications@github.com> wrote:

@Koenkk<https://github.com/Koenkk>

@mdn-united<https://github.com/mdn-united> so can you control both gangs by sending over MQTT to zigbee2mqtt/0x00158d000258456b/set ON and zigbee2mqtt/0x00158d00025d7a9e/set ON and

I don't know how to do it. Just typing "zigbee2mqtt/0x00158d000258456b/set ON" didn't work.
But if I simulate switching with ioBroker it works. If I want to change the other side of the switch I have to select another device.
[grafik]<https://user-images.githubusercontent.com/11157159/52846028-db48ee00-3108-11e9-9846-392c902eabd1.png>
[grafik]<https://user-images.githubusercontent.com/11157159/52846054-ec91fa80-3108-11e9-9817-8566f0f662eb.png>
[grafik]<https://user-images.githubusercontent.com/11157159/52846199-501c2800-3109-11e9-8354-d1d3aa44ce4a.png>

Here is a picture from the switch with the front removed. To me it looks like two devices in one case.
[20190215_101101]<https://user-images.githubusercontent.com/11157159/52846575-3fb87d00-310a-11e9-8327-8aa3b39ef1f8.jpg>

btw: I don't know what a pull request is. I'm a Windows Server admin, not a developer. I've never worked with Github before. But I'm willing to do my part to make the Zigbee adapter compatible with various devices. This is my first device, so I need more help and instructions. Next time I will be able to give you the necessary information straightaway.

**Comment by ryanbeaton** [comment]
That looks like a Euro (86 style) the 3A/Nue stuff has been Australian so far. Do you have a link to that device?

**Comment by mdn-united** [comment]
@highground88 Thank you for mentioning MQTT.fx. I can connect to my the mosquito server and the switch is also paired with it and I see changes when I press a button on the switch: 
![grafik](https://user-images.githubusercontent.com/11157159/52853036-9af26b80-311a-11e9-9770-de051e3c1006.png)

But I have no luck using MQTT.tx, but I not sure if I'm doing it right.
![grafik](https://user-images.githubusercontent.com/11157159/52853128-e573e800-311a-11e9-8234-47f0dbf233ff.png)
I also tried different syntax and this is what I find in the logs:
```
MqttFX ClientModel : sucessfully published message "state":"ON" to topic zigbee2mqtt/0x00158d000258456b (QoS 0, Retained: false)
PublishController  : publish
MqttFX ClientModel : attempt to add PublishTopic
MqttFX ClientModel : sucessfully published message {"state":"ON"} to topic zigbee2mqtt/0x00158d000258456b (QoS 0, Retained: false)
PublishController  : publish
MqttFX ClientModel : attempt to add PublishTopic
MqttFX ClientModel : sucessfully published message {"set":"ON"} to topic zigbee2mqtt/0x00158d000258456b (QoS 0, Retained: false)
PublishController  : publish
MqttFX ClientModel : attempt to add PublishTopic
MqttFX ClientModel : sucessfully published message {"set" "ON"} to topic zigbee2mqtt/0x00158d000258456b (QoS 0, Retained: false)
PublishController  : publish
MqttFX ClientModel : attempt to add PublishTopic
MqttFX ClientModel : sucessfully published message {set ON} to topic zigbee2mqtt/0x00158d000258456b (QoS 0, Retained: false)
PublishController  : publish
MqttFX ClientModel : attempt to add PublishTopic
MqttFX ClientModel : sucessfully published message set ON to topic zigbee2mqtt/0x00158d000258456b (QoS 0, Retained: false)
```

**Comment by mdn-united** [comment]
hi @ryanbeaton, I found it on Amazon (Germany): https://www.amazon.de/dp/B07GWR3VBX

**Comment by Koenkk** [comment]
@mdn-united you should use topic `zigbee2mqtt/0x00158d000258456b/set` with payload `ON`. In the screenshot you use `zigbee2mqtt/0x00158d000258456b` with payload `set ON`.

**Comment by mdn-united** [comment]
@Koenkk ok, I tried what you suggested but it didn't work either. 
```
2019-02-15 23:12:07,066  INFO --- MqttFX ClientModel             : sucessfully published message On to topic zigbee2mqtt/0x00158d000258456b/set (QoS 0, Retained: false)
2019-02-15 23:12:18,174  INFO --- PublishController              : publish
2019-02-15 23:12:18,175  INFO --- MqttFX ClientModel             : attempt to add PublishTopic
2019-02-15 23:12:18,175  INFO --- MqttFX ClientModel             : sucessfully published message on to topic zigbee2mqtt/0x00158d000258456b/set (QoS 0, Retained: false)
2019-02-15 23:12:22,790  INFO --- PublishController              : publish
2019-02-15 23:12:22,791  INFO --- MqttFX ClientModel             : attempt to add PublishTopic
2019-02-15 23:12:22,791  INFO --- MqttFX ClientModel             : sucessfully published message ON to topic zigbee2mqtt/0x00158d000258456b/set (QoS 0, Retained: false)
2019-02-15 23:12:41,766  INFO --- PublishController              : publish
2019-02-15 23:12:41,767  INFO --- MqttFX ClientModel             : attempt to add PublishTopic
2019-02-15 23:12:41,767  INFO --- MqttFX ClientModel             : sucessfully published message ON to topic zigbee2mqtt/0x00158d000258456b/set (QoS 0, Retained: false)
2019-02-15 23:15:18,523  INFO --- PublishController              : publish
```
Here is what I see on the Raspberry:```

zigbee2mqtt:error 2019-2-15 23:12:08 No converter available for 'state' (On)
zigbee2mqtt:error 2019-2-15 23:12:19 No converter available for 'state' (on)
zigbee2mqtt:error 2019-2-15 23:12:24 No converter available for 'state' (ON)
```

Is there a list of common commands that I could test?
Or is there a way to read all the available commands from the device?

**Comment by Koenkk** [comment]
What did you add to `devices.js` for this device?

**Comment by mdn-united** [comment]
I added this:
```
// 3A Zigbee 3.0 Smart Switch
    {
	zigbeeModel: ['FNB56-ZSW01LX2.0'],		
	model: 'HGZB-42-UK',
	vendor: '3A',
	description: 'Zigbee 3.0 Smart Switch 2 Gang ',
	supports: 'on and off',	
	fromZigbee: [fz.WXKG01LM_click,fz.light_state], 
	toZigbee: [],
    },
```

**Comment by Koenkk** [comment]
Please try with

```js
 // 3A Zigbee 3.0 Smart Switch
   {
        zigbeeModel: ['FNB56-ZSW01LX2.0'],
        model: 'HGZB-42-UK',
	description: 'Zigbee 3.0 Smart Switch 2 Gang ',
        vendor: '3A',
        supports: 'on/off',
        fromZigbee: [fz.ignore_onoff_change, fz.generic_state],
        toZigbee: [tz.on_off],
   },
```

**Comment by mdn-united** [comment]
hey @Koenkk , it actually worked! 
I tried ON and OFF an both commands where recognized and the switch changed it's state. 

Here is the MQTTfx log:
```
MqttFX ClientModel: attempt to add PublishTopic
MqttFX ClientModel: sucessfully published message ON to topic zigbee2mqtt/0x00158d000258456b/set (QoS 0, Retained: false)
PublishController : publish
MqttFX ClientModel: attempt to add PublishTopic
MqttFX ClientModel: addPublishTopic : zigbee2mqtt/0x00158d00025d7a9e/set
MqttFX ClientModel: sucessfully published message ON to topic zigbee2mqtt/0x00158d00025d7a9e/set (QoS 0, Retained: false)
PublishController : publish
MqttFX ClientModel: attempt to add PublishTopic
MqttFX ClientModel: sucessfully published message OFF to topic zigbee2mqtt/0x00158d00025d7a9e/set (QoS 0, Retained: false)
PublishController : publish
MqttFX ClientModel: attempt to add PublishTopic
MqttFX ClientModel: sucessfully published message OFF to topic zigbee2mqtt/0x00158d000258456b/set (QoS 0, Retained: false)
``` 
And here is what zigbee2mqtt said:
```
Device incoming...
MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
Device incoming...
MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
Zigbee publish to device '0x00158d000258456b', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - null
MQTT publish: topic 'zigbee2mqtt/0x00158d000258456b', payload '{"state":"ON","linkquality":139}'
MQTT publish: topic 'zigbee2mqtt/0x00158d000258456b', payload '{"state":"ON","linkquality":141}'
Zigbee publish to device '0x00158d00025d7a9e', genOnOff - on - {} - {"manufSpec":0,"disDefaultRsp":0} - null
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"ON","contact":true,"linkquality":110}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"ON","contact":true,"linkquality":147}'
Zigbee publish to device '0x00158d00025d7a9e', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"OFF","contact":true,"linkquality":147}'
Zigbee publish to device '0x00158d000258456b', genOnOff - off - {} - {"manufSpec":0,"disDefaultRsp":0} - null
MQTT publish: topic 'zigbee2mqtt/0x00158d000258456b', payload '{"state":"OFF","linkquality":141}'
MQTT publish: topic 'zigbee2mqtt/0x00158d000258456b', payload '{"state":"OFF","linkquality":136}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"OFF","contact":true,"linkquality":144}'
```
But since I changed `fromZigbee: [fz.WXKG01LM_click,fz.light_state],` to `fromZigbee: [fz.ignore_onoff_change, fz.generic_state],` it doesn't recognize a long press. 

When I switch back to `fromZigbee: [fz.WXKG01LM_click,fz.light_state],` I see "long" (off) and "long_release" (on) whenever I pressed the buttons a bit longer. Like this:
```
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"ON","contact":true,"linkquality":131}'
MQTT publish: topic 'zigbee2mqtt/0x00158d000258456b', payload '{"state":"ON","linkquality":136}'
MQTT publish: topic 'zigbee2mqtt/0x00158d000258456b', payload '{"state":"OFF","linkquality":136}'
MQTT publish: topic 'zigbee2mqtt/0x00158d000258456b', payload '{"state":"OFF","linkquality":126,"click":"long"}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"OFF","contact":true,"linkquality":131}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"OFF","contact":true,"linkquality":136,"click":"long"}'
MQTT publish: topic 'zigbee2mqtt/0x00158d000258456b', payload '{"state":"OFF","linkquality":134,"click":"long_release","duration":6888}'
MQTT publish: topic 'zigbee2mqtt/0x00158d000258456b', payload '{"state":"ON","linkquality":136}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"OFF","contact":true,"linkquality":131,"click":"long_release","duration":9060}'
MQTT publish: topic 'zigbee2mqtt/0x00158d00025d7a9e', payload '{"state":"ON","contact":true,"linkquality":131}'
MQTT publish: topic 'zigbee2mqtt/0x00158d000258456b', payload '{"state":"OFF","linkquality":136}'
MQTT publish: topic 'zigbee2mqtt/0x00158d000258456b', payload '{"state":"OFF","linkquality":128,"click":"long"}'
MQTT publish: topic 'zigbee2mqtt/0x00158d000258456b', payload '{"state":"OFF","linkquality":128,"click":"long_release","duration":4327}'
MQTT publish: topic 'zigbee2mqtt/0x00158d000258456b', payload '{"state":"ON","linkquality":136}'
```

**Comment by Koenkk** [comment]
Normally we dont support this long click for these kind of devices. I would recommend the configuration I provided, could you make a pr with this?

**Comment by mdn-united** [comment]
hi @Koenkk , I don't know how a pull request works and I don't know what to do. I just want that switch to be usable in ioBroker - for me and other users. 
Now I'm just running out of days to send the switch back. I don't want to end up with some 40€ hardware scrap. 
I really want to contribute to the compatibility list, but this is getting much harder than I expected. I need some help!!

**Comment by Koenkk** [comment]
@mdn-united no problem, added the device.

@kirovilya now has to update iobroker to add support for this device.
