### ISSUE TITLE
Question: fromZigbee.js type 'devChange' vs. 'attReport'?

### ISSUE THREAD

**Issue by felixstorm** [Koenkk/zigbee-shepherd-converters#289]
When trying to take first steps to implement support for ubisys J1 (window cover) devices, I noticed that I get identical notifications of type 'devChange' and 'attReport' whenever an attribute configured for reporting changes.
```
2/18/2019, 9:39:54 PM - warn: No converter available for 'J1' with cid 'closuresWindowCovering', type 'attReport' and data '{"cid":"closuresWindowCovering","data":{"currentPositionLiftPercentage":0}}'
2/18/2019, 9:39:54 PM - warn: No converter available for 'J1' with cid 'closuresWindowCovering', type 'devChange' and data '{"cid":"closuresWindowCovering","data":{"currentPositionLiftPercentage":0}}'
```
What is the difference between the two and which one would you suggest I implement (and probably ignore the other)?

Thanks,  
Felix

**Comment by Koenkk** [comment]
I could be wrong, but AFAIK `attReport` event is always generated when a device reports a message, `devChange` only when the values change.

I would recommend to base your converter on `attReport`

**Comment by dlashua** [comment]
attReport events happen on attribute changes when device.report() has been issued. devChange happens as a response after you write an attribute, when you specifically read a particular attribute, or when the device decides to send it to the coordinator even though it hasn't been specifically requested. 

To be as comprehensive as possible, there is also statusChange which doesn't seem to be documented on the zigbee-shepherd wiki but is the message type you get from a report after using the enroll procedure. To my knowledge, this only happens with ssIasZone cids, but, I could be wrong.

**Comment by felixstorm** [comment]
@Koenkk , @dlashua - thanks for your answers and also thanks for pointing me at the zigbee-shepherd wiki again. I had been looking for it before, but had only checked the local version, but not the one at zigbeer which does provide all the information I was looking for.
