### ISSUE TITLE
Question: is ZCL / Closure -> Window Covering cluster supported ?

### ISSUE THREAD

**Issue by mchacher** [Koenkk/zigbee-shepherd-converters#291]
I only saw a Xiaomi device with a partial cluster implementation. I am trying a "not yet" released Zigbee puck to the market. Thanks for your help.

**Comment by Koenkk** [comment]
Yes: https://github.com/Koenkk/zcl-id/blob/master/definitions/cluster_defs.json#L400

**Comment by mchacher** [comment]
Thanks for your support. 

As far as I understand, I will have to write my own converters (Zigbee2MQTT and MQTT2Zigbee) since there is no generic converters for this cluster (window covering). Correct ?

Your documentation is excellent overall and you code super clean and very well structure. If you can provide further inputs on how to create specific devices (configure section) and how to create converters this would be a dream!

**Comment by Koenkk** [comment]
Yes, you have to write your own converters (as none are available yet in zigbee-shepherd-converters). Just create a new issue with the device you want to support.
