### ISSUE TITLE
Add another GledOpto device.

### ISSUE THREAD

**Issue by bochelork** [Koenkk/zigbee-shepherd-converters#293]
Just added this device:
https://www.aliexpress.com/item/GLEDOPTO-ZIGBEE-LED-10W-floodlight-RGB-CCT-warm-white-and-cool-white-zigbee-light-link-AC110/32957140430.html
Just added 'GL-FL-004TZ' to the first GledOpto device in the list. Works like a charm.

    // Gledopto
    {
        zigbeeModel: ['GLEDOPTO', 'GL-C-008', 'GL-C-007', 'GL-FL-004TZ'],
        model: 'GL-C-008',
        vendor: 'Gledopto',
        description: 'Zigbee LED controller RGB + CCT / RGBW / WWCW / Dimmer',
        extend: generic.light_onoff_brightness_colortemp_colorxy,
        ep: (device) => {
            if (device.epList.toString() === '11,12,13') {
                return {'': 12};
            } else if (device.epList.toString() === '10,11,13' || device.epList.toString() === '11,13') {
                return {'': 11};
            } else {
                return {};
            }
        },
    },

**Comment by Koenkk** [comment]
Added, thanks.
