### ISSUE TITLE
Add support for Stelpro Orleans baseboard thermostat (ST218)

### ISSUE THREAD

**Issue by goldriver2** [Koenkk/zigbee-shepherd-converters#295]
Hi

I have no clue as to how to do a PR to add something to GITHUB but for anyone interested, here is the changes I added to my device.js to get it to work:

const devices = [
    // Stelpro Orleans baseboard thermostat
    {
        zigbeeModel: ['ST218'],
        model: 'ST218',
        vendor: 'Stelpro',
        description: 'Baseboard integrated zigbee Thermostat ',
        supports: 'temperature ',
        fromZigbee: [
            fz.thermostat_att_report, fz.thermostat_dev_change,
        ],
        toZigbee: [
            tz.thermostat_local_temperature, tz.thermostat_occupied_heating_setpoint,
            tz.thermostat_pi_heating_demand,
        ],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 25);
            const actions = [
                (cb) => device.bind('genBasic', coordinator, cb),
                (cb) => device.bind('genIdentify', coordinator, cb),
                (cb) => device.bind('genGroups', coordinator, cb),
                (cb) => device.bind('hvacThermostat', coordinator, cb),
                (cb) => device.bind('hvacUserInterfaceCfg', coordinator, cb),
                (cb) => device.bind('msTemperatureMeasurement', coordinator, cb),
                (cb) => device.report('hvacThermostat', 'localTemp', 300, 3600, 0, cb),
                ];
            execute(device, actions, callback); 
         },
    },

as for the tozigbee.js and fromzigbee.js, I used the already existing ones and everything seems to work

**Comment by Koenkk** [comment]
Can you post the toZigbee.js you are using? (thermostat_pi_heating_demand) is missing from latest version, I want to know which one it was.

**Comment by goldriver2** [comment]
here it is ..

[toZigbee.zip](https://github.com/Koenkk/zigbee-shepherd-converters/files/2895842/toZigbee.zip)

**Comment by Koenkk** [comment]
Added!
