### ISSUE TITLE
Visonic MCT-350 - IAS device

### ISSUE THREAD

**Issue by j4c3** [Koenkk/zigbee-shepherd-converters#296]
I inherited a handful of Visonic MCT-350 magnetic door sensors.  In the US, they're used / sold as part of the Xfinity Home solutions.  I'm new to zigbee, and have made some progress, but the IAS devices seem a bit more complicated. 

I added a devices.js entry, and the 'base' configure: entries I'd seen for IAS items.  This got me some progress.

The log is here: https://pastebin.com/wDpjX8cj  We see the device sending some signals.  statusChange with a zoneStatus of 32 is closed, and 33 is open.  It also sends a report of batteryVoltage.  What I'm not sure how to handle is that the message being received for those is of device 'undefined' and the ID there is the same as my coordinator. 

Let me know if this is not the proper venue for this discussion.

Thanks!

**Comment by Koenkk** [comment]
Please try with the latest dev firmware (doesn't require re-pairing of devices), this should fix the undefined/message from coordinator errors which are holding you from continuing. (https://github.com/Koenkk/Z-Stack-firmware/tree/dev/coordinator/CC2531/bin)

**Comment by j4c3** [comment]
Looks like that did it.  

```
zigbee2mqtt:info 2019-2-22 21:03:33 Succesfully configured TEST MCT-350 (0x000d6f000ccfb76c)
zigbee2mqtt:debug 2019-2-22 21:04:36 Received zigbee message of type 'attReport' with data '{"cid":"genPowerCfg","data":{"batteryVoltage":26}}' of device 'MCT-350 SMA' (0x000d6f000ccfb76c)
```

Thanks again!

**Comment by j4c3** [comment]
Well, maybe.  Upon restarting zigbee2mqtt, I see: 
`zigbee2mqtt:error 2019-2-22 21:57:31 Failed to configure MCT-350 (1) (0x000d6f000ccfb76c) ('Error: AF data request fails, status code: 240. MAC transaction expired.')`

But, activating it still generates messages:
`zigbee2mqtt:warn 2019-2-22 21:57:35 No converter available for 'MCT-350 SMA' with cid 'ssIasZone', type 'statusChange' and data '{"cid":"ssIasZone","zoneStatus":33}'
zigbee2mqtt:debug 2019-2-22 21:57:35 Received zigbee message of type 'statusChange' with data '{"cid":"ssIasZone","zoneStatus":33}' of device 'MCT-350 SMA' (0x000d6f000ccfb76c)`

Not 100% sure yet, but in this state, I haven't seen it report a battery status.

**Comment by Koenkk** [comment]
The configure only has to succeed once, it's not strange that this could fail the next time, as the device is probably sleeping.

Can you add to `devices.js`:

```js
{
        zigbeeModel: ['MCT-350 SMA'],
        model: 'MCT-350',
        vendor: 'Visonic',
        description: 'Door and window contact sensor',
        supports: 'contact',
        fromZigbee: [fz.heiman_contact],
        toZigbee: [],
    },
```

**Comment by j4c3** [comment]
It looks good.  I can't tell the low battery reporting, yet, but the tamper is correct.  I wasn't sure if contact: true would mean that the the device should be closed, or if the contact sensor had been triggered.  

I just got a Aqara door/window sensor, and the True/False for Closed/Open on that device are opposite from the MCT-350 (False when closed, True when open) using the heiman_contact converter. 

Thanks!

**Comment by Koenkk** [comment]
Contact should be true when the door is closed, current behaviour is wrong.

Add to:

**devices.js**

```
{
        zigbeeModel: ['MCT-350 SMA'],
        model: 'MCT-350',
        vendor: 'Visonic',
        description: 'Door and window contact sensor',
        supports: 'contact',
        fromZigbee: [fz.visonic_contact],
        toZigbee: [],
    },
```

**fromZigbee.js**
```js
visonic_contact: {
        cid: 'ssIasZone',
        type: 'statusChange',
        convert: (model, msg, publish, options) => {
            const zoneStatus = msg.data.zoneStatus;
            return {
                contact: !((zoneStatus & 1) > 0), // Bit 1 = Alarm: Contact detection
                tamper: (zoneStatus & 1<<2) > 0, // Bit 3 = Tamper status
                battery_low: (zoneStatus & 1<<3) > 0, // Bit 4 = Battery LOW indicator
            };
        },
    },
```

If this works, please make a pull request.
