### ISSUE TITLE
osram mini switch

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee-shepherd-converters#313]
i have here a osram mini switch. with 3 buttons...
it works with https://github.com/Koenkk/zigbee-shepherd-converters/pull/312

but i have here many hue bulbs connected with same cc2531 also.. the issue is the switch can on/of all connected hue bulbs without the program (zigbee2mqtt) is running.. 

any ideas ??

**Comment by Koenkk** [comment]
This looks the same as https://github.com/Koenkk/zigbee2mqtt/issues/962, right?

**Comment by arteck** [comment]
yes.. this is my problem ..

**Comment by Koenkk** [comment]
Ok, to keep everything in one place, we should continue there.
