### ISSUE TITLE
Aqara QBKG04LM uses wrong endpoint for setting on/off

### ISSUE THREAD

**Issue by asgothian** [Koenkk/zigbee-shepherd-converters#355]
I have a Aqara single key wall switch without neutral (QBKG04LM) which does not react to any attempt to change the state from iobroker. When changing the state from iobroker, the system responds with a timeout error message (see this issue: https://github.com/ioBroker/ioBroker.zigbee/issues/258). I have verified that the system attempts to set the on.off on endpoint 1, which does not respond to the message. The correct endpoint for this is EP 2.
Digging through the history (since older versions were reported to have worked), i found that a change was made to the switch from
```
 toZigbee: [tz.on_off],
 ep: (device) => {
       return {'': 2};
 }
```
to 

```
   toZigbee: [tz.on_off, tz.xiaomi_switch_operation_mode],
    ep: (device) => {
         return {'system': 1, 'default': 2};
    }
```

Effectively disabling the switch.

I was unable to find which pull request was involved, and what the reason for this change was, but would ask for this to be reviewed and fixed.

**Comment by asgothian** [comment]
I spent some more time digging around. Apparently, the PR #287 introduced this change. @KapJI does mention that this is supposed to work with the QBKG04LM switch.

**Comment by KapJI** [comment]
This changed how default endpoint is chosen in zigbee2mqtt: https://github.com/Koenkk/zigbee2mqtt/pull/1114
I guess ioBroker.zigbee needs something similar.

**Comment by asgothian** [comment]
Thanks for the hint. I'll take a closer look at that.

**Comment by asgothian** [comment]
OK.. found a solution in iobroker.. closing this.
