### ISSUE TITLE
Aqara device issue on update.

### ISSUE THREAD

**Issue by j4c3** [Koenkk/zigbee-shepherd-converters#385]
I have a number of Aqara devices, currently working, using a copy of the zigbee-shepherd-converters from 2/20.  When I update to a new version, 4/2, they stop working.  Other devices (some MCT-350s) continue to work as expected.  Was there a change in handling model/modelID, vs using the zigbeeModel?

Working with 2/20:
`zigbee2mqtt:debug 4/3/2019, 7:48:25 AM Received zigbee message of type 'attReport' with data '{"cid":"msTemperatureMeasurement","data":{"measuredValue":1861}}' of device 'lumi.weather' (0x00158d000303c8a1)`

`zigbee2mqtt:info 4/3/2019, 7:48:25 AM MQTT publish: topic 'zigbee2mqtt/aqaraTemp_2', payload {"temperature":18.61,"linkquality":68,"humidity":52.15,"pressure":1003.1,"battery":74,"voltage":2955}'`

Not working with 4/2:
`zigbee2mqtt:debug 4/3/2019, 7:56:37 AM Received zigbee message of type 'attReport' with data '{"cid":"msTemperatureMeasurement","data":{"measuredValue":1860}}' of device 'lumi.weather' (0x00158d000303c8a1)`

`zigbee2mqtt:warn 4/3/2019, 7:56:37 AM No converter available for 'WSDCGQ11LM' with cid 'msTemperatureMeasurement', type 'attReport' and data '{"cid":"msTemperatureMeasurement","data":{"measuredValue":1860}}'`

`zigbee2mqtt:warn 4/3/2019, 7:56:37 AM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.`

**Comment by Koenkk** [comment]
Shouldn't be the case, why are you using a custom zigbee-shepherd-converters?

**Comment by j4c3** [comment]
I am running in docker.  I mapped that directory out to add new devices, and updated with git.  The error still happens when I unmap that directory.

**Comment by Koenkk** [comment]
Can you post your zigbee2mqtt stratup log? With what command are you running the docker container?

**Comment by j4c3** [comment]
My docker command is: 
docker run --name zigbee2mqtt \
 -d \
 --net=bridge \
 -v /share/CACHEDEV1_DATA/Store/HomeAutomation/zigbee2mqtt/data:/app/data \
 -v /share/CACHEDEV1_DATA/Store/HomeAutomation/zigbee2mqtt/shepherd-converters:/app/node_modules/zigbee-shepherd-converters \
 -v /etc/TZ:/etc/TZ:ro \
 -v /etc/localtime:/etc/localtime:ro \
 -e USER_ID=999 \
 -e GROUP_ID=99 \
 --restart=always \
 --device=/dev/ttyACM0 \
 koenkk/zigbee2mqtt:latest

And log below.  The startup from working and not display the same 36 lines. 

4/3/2019, 7:50:19 AM - info: Logging to directory: '/app/data/log/2019-04-03.07-50-19'
4/3/2019, 7:50:19 AM - debug: Removing old log directory '/app/data/log/2019-04-01.13-05-36'
4/3/2019, 7:50:20 AM - debug: Using zigbee-shepherd with settings: '{"net":{"panId":6754,"extPanId":[221,221,221,221,221,221,221,221],"channelList":[11],"precfgkey":"HIDDEN"},"dbPath":"/app/data/database.db","sp":{"baudRate":115200,"rtscts":true}}'
4/3/2019, 7:50:20 AM - debug: Loaded state from file /app/data/state.json
4/3/2019, 7:50:20 AM - debug: Saving state to file /app/data/state.json
4/3/2019, 7:50:20 AM - info: Starting zigbee2mqtt version 1.2.1 (commit #e5ca977)
4/3/2019, 7:50:20 AM - info: Starting zigbee-shepherd
4/3/2019, 7:50:21 AM - info: zigbee-shepherd started
4/3/2019, 7:50:21 AM - info: Coordinator firmware version: '20190223'
4/3/2019, 7:50:21 AM - debug: zigbee-shepherd info: {"enabled":true,"net":{"state":"Coordinator","channel":11,"panId":"0x1a62","extPanId":"0xdddddddddddddddd","ieeeAddr":"0x00124b000e8969a1","nwkAddr":0},"firmware":{"transportrev":2,"product":0,"version":"2.6.3","revision":20190223},"startTime":1554310221,"joinTimeLeft":0}
4/3/2019, 7:50:21 AM - info: Currently 9 devices are joined:
4/3/2019, 7:50:21 AM - info: MCT350_3 (0x000d6f000ccfb76c): MCT-350 SMA - Visonic Magnetic door & window contact sensor (EndDevice)
4/3/2019, 7:50:21 AM - info: MCT350_2 (0x000d6f000cd39cda): MCT-350 SMA - Visonic Magnetic door & window contact sensor (EndDevice)
4/3/2019, 7:50:21 AM - info: MCT350_1 (0x000d6f000ccfc30d): MCT-350 SMA - Visonic Magnetic door & window contact sensor (EndDevice)
4/3/2019, 7:50:21 AM - info: aqaraTemp_4 (0x00158d000303c94c): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
4/3/2019, 7:50:21 AM - info: aqaraTemp_1 (0x00158d00025d8f22): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
4/3/2019, 7:50:21 AM - info: aqaraTemp_2 (0x00158d000303c8a1): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
4/3/2019, 7:50:21 AM - info: aqaraTemp_3 (0x00158d000303c90b): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
4/3/2019, 7:50:21 AM - info: aqaraContact_1 (0x00158d0002c8d457): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
4/3/2019, 7:50:21 AM - info: aqaraContact_2 (0x00158d000312dada): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
4/3/2019, 7:50:21 AM - info: Zigbee: disabling joining new devices.
4/3/2019, 7:50:21 AM - info: Connecting to MQTT server at mqtt://192.168.1.101
4/3/2019, 7:50:21 AM - info: zigbee-shepherd ready
4/3/2019, 7:50:21 AM - info: Connected to MQTT server
4/3/2019, 7:50:21 AM - info: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
4/3/2019, 7:50:21 AM - info: MQTT publish: topic 'zigbee2mqtt/MCT350_3', payload '{"contact":true,"tamper":false,"battery_low":false,"linkquality":44}'
4/3/2019, 7:50:21 AM - info: MQTT publish: topic 'zigbee2mqtt/MCT350_2', payload '{"contact":true,"tamper":false,"battery_low":false,"linkquality":31}'
4/3/2019, 7:50:21 AM - info: MQTT publish: topic 'zigbee2mqtt/MCT350_1', payload '{"contact":true,"tamper":false,"battery_low":false,"linkquality":49}'
4/3/2019, 7:50:21 AM - info: MQTT publish: topic 'zigbee2mqtt/aqaraTemp_4', payload '{"temperature":18.75,"linkquality":63,"humidity":52.4,"pressure":1003.2,"battery":74,"voltage":2955}'
4/3/2019, 7:50:21 AM - info: MQTT publish: topic 'zigbee2mqtt/aqaraTemp_1', payload '{"temperature":18.67,"linkquality":78,"humidity":51.6,"pressure":1002.5,"battery":80,"voltage":2965}'
4/3/2019, 7:50:21 AM - info: MQTT publish: topic 'zigbee2mqtt/aqaraTemp_2', payload '{"temperature":18.61,"linkquality":68,"humidity":52.18,"pressure":1003,"battery":74,"voltage":2955}'
4/3/2019, 7:50:21 AM - info: MQTT publish: topic 'zigbee2mqtt/aqaraTemp_3', payload '{"temperature":17.09,"linkquality":47,"humidity":54.94,"pressure":1003.6,"battery":86,"voltage":2975}'
4/3/2019, 7:50:21 AM - info: MQTT publish: topic 'zigbee2mqtt/aqaraContact_1', payload '{"contact":true,"linkquality":70,"battery":91,"voltage":2985}'
4/3/2019, 7:50:21 AM - info: MQTT publish: topic 'zigbee2mqtt/aqaraContact_2', payload '{"contact":true,"linkquality":52,"battery":100,"voltage":3015}'
4/3/2019, 7:50:21 AM - info: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"log_level":"debug","permit_join":false}'
4/3/2019, 7:50:21 AM - debug: Mounted the cieApp (epId 11)

**Comment by Koenkk** [comment]
Please run with 

```bash
docker run --name zigbee2mqtt 
-d 
--net=bridge 
-v /share/CACHEDEV1_DATA/Store/HomeAutomation/zigbee2mqtt/data:/app/data 
-v /etc/TZ:/etc/TZ:ro 
-v /etc/localtime:/etc/localtime:ro 
-e USER_ID=999 
-e GROUP_ID=99 
--restart=always 
--device=/dev/ttyACM0 
koenkk/zigbee2mqtt:latest
```

**Comment by j4c3** [comment]
Arg!  I swear I had already done that, but it worked fine this time.  The build was from 2019/03/14.

So, I blew that one away, and tried the latest-dev.  Which... also worked. 

Sorry to waste your time with a false alarm.
