### ISSUE TITLE
Add Gledopto GL-S-004Z

### ISSUE THREAD

**Issue by ArJay60** [Koenkk/zigbee-shepherd-converters#390]
Add this device:
https://nl.aliexpress.com/item/GLEDOPTO-zigbee-ww-cw-dimmer-GU10-bulu-LED-spotlight-5-W-ZLL-smart-APP-controll-AC100/32894864409.html 

    {
        zigbeeModel: ['GL-S-004Z'],
        model: 'GL-S-004Z',
        vendor: 'Gledopto',
        description: 'Zigbee Smart WW/CW GU10',
        extend: gledopto.light_onoff_brightness_colortemp,
        ep: (device) => {
            if (device.epList.toString() === '11,12,13') {
                return {'': 12};
            } else if (device.epList.toString() === '10,11,13' || device.epList.toString() === '11,13') {
                return {'': 11};
            } else {
                return {};
            }
        },
    },

**Comment by Koenkk** [comment]
done, thanks!
