### ISSUE TITLE
Issue with Aqara wall switch QBKG11LM (Single with L+N)

### ISSUE THREAD

**Issue by zvldz** [Koenkk/zigbee-shepherd-converters#419]
Hi
I have the same problem as https://github.com/Koenkk/zigbee-shepherd-converters/issues/405
Maybe need to do the same fix for QBKG11LM.

`Apr 23 23:26:12 Khadas npm[4738]: zigbee2mqtt:debug 4/23/2019, 11:26:12 PM Received zigbee message of type 'attReport' with data '{"cid":"genMultistateInput","data":{"presentValue":1}}' of device 'lumi.ctrl_ln1.aq1' (0x00158d000211434a) of endpoint 5`

**Comment by zvldz** [comment]
Or need a PR with a patch?

**Comment by Koenkk** [comment]
Yes, please make a pr

**Comment by zvldz** [comment]
Created.

**Comment by zvldz** [comment]
Fixed https://github.com/Koenkk/zigbee-shepherd-converters/pull/420
