### ISSUE TITLE
New device: Philips Hue Bloom

### ISSUE THREAD

**Issue by jaaps** [Koenkk/zigbee-shepherd-converters#42]
I got a Philips Hue Bloom and tried to add it to zigbee2mqtt. The device supports brightness and rgb but no kelvin levels. I have added the following to devices.js.

```
    {
        zigbeeModel: ['LLC012'],
        model: '7299760PH',
        vendor: 'Philips',
        description: 'Hue Bloom',
        supports: generic.light_onoff_brightness_colorxy().supports,
        fromZigbee: generic.light_onoff_brightness_colorxy().fromZigbee,
        toZigbee: generic.light_onoff_brightness_colorxy().toZigbee,
    },
```

This seems to work however in Home-Assistant when changing kelvin levels instead of getting the closest rgb value I instead get the following in my zigbee2mqtt log: 

> ERROR No converter available for 'color_temp' (460)

Colors, brightness and on/off work fine.

Not sure what I'm doing wrong. I'm using the DEV branch of zigbee2mqtt.

**Comment by Koenkk** [comment]
If this device doesn't support kelvin levels, home assistant shouldn't show the color temperature slider, right?

**Comment by jaaps** [comment]
It seems home-assistant still has the old values from mqtt auto discovery. I originally tested it by copying the Hue Go part. Can I just delete the line from the database and re-pair?

**Comment by jaaps** [comment]
Ok, I have figured it out.

To support my Philips Hue bloom the following is needed:

zigbee-shepherd-converters/devices.js: devices
`    {
        zigbeeModel: ['LLC012'],
        model: '7299760PH',
        vendor: 'Philips',
        description: 'Hue Bloom',
        supports: generic.light_onoff_brightness_colorxy().supports,
        fromZigbee: generic.light_onoff_brightness_colorxy().fromZigbee,
        toZigbee: generic.light_onoff_brightness_colorxy().toZigbee,
    },
`

zigbee2mqtt/lib/homeassistant.js: mapping
` '7299760PH': [configurations.light_brightness_xy],`

**Comment by Koenkk** [comment]
Merged, thanks!

**Comment by aep** [comment]
jo, does the bloom require a differemt pairing procedure? the 10s reset with dimmer doesnt do it for me.

**Comment by aep** [comment]
yeah, also tried touchlink by putting cc stick, bridge and bloom near to each other and then using the hue touchlink api. 

It pairs fine with the hue, but not with cc. I suspect it wont join an HA network anymore after its been in an LL network. Did you previously pair yours with the hue bridge?

**Comment by jaaps** [comment]
Mine was previously paired with the hue bridge. My hue bridge was disconnected when pairing things with zigbee2mqtt however. But you probably tried that already.

**Comment by aep** [comment]
yeah. but you gave me an idea so i went and depowered every hue device in my home
unfortunately no dice either.

just to confirm, what worked for you was:
- depower hue bridge
- 10s on+scene 1 on the round dimmer thing until the bloom blinks and then becomes red
- power cycle the bloom
- permit_join: true and then just wait

**Comment by jaaps** [comment]
This worked for me:

- Depower bridge
- Disconnect Bloom power
- Reconnect Bloom power
- 10s on 1 and 0 on this remote https://www2.meethue.com/en-us/p/hue-dimmer-switch/046677458140
- After around 10s bloom changes color, keep a few second longer pressed and then it should connect.

**Comment by aep** [comment]
thanks for your help, i think i need to give up.
even got the same remote as you.

mine blinks, then goes red and stays that way, not joining.   It's a pretty old device so maybe back then they didnt allow HA.

**Comment by zgadgeter** [comment]
Hello, anything new on this of how to connect the bloom to zigbee? thanks.
