### ISSUE TITLE
Newbie trying to contribute to add support for Votaar Smart Plug

### ISSUE THREAD

**Issue by duesseldorferjung** [Koenkk/zigbee-shepherd-converters#421]
Good Day Community,
this is my first time using Github so please support me to support.

I have succesfully haijecked Osram + Plug entry to support Votaar Smart Plug using custom device.

`    {
        zigbeeModel: ['FB56-SKT17AC1.4'],
        model: 'AB3257001NJ',
        description: 'Smart+ plug',
        supports: 'on/off',
        vendor: 'OSRAM',
        fromZigbee: [fz.ignore_onoff_change, fz.state],
        toZigbee: [tz.on_off],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 3);
            const cfg = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 1000, repChange: 0};
            const actions = [
                (cb) => device.bind('genOnOff', coordinator, cb),
                (cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg, cb),
            ];

            execute(device, actions, callback);
        },
    },`

From my understanding Vendor and Description still Need to be change like I did here that it can be added to the new Version.
`    {
        zigbeeModel: ['FB56-SKT17AC1.4'],
        model: 'AB3257001NJ',
        description: 'votaar Smart Plug',
        supports: 'on/off',
        vendor: 'ANCHOR',
        fromZigbee: [fz.ignore_onoff_change, fz.state],
        toZigbee: [tz.on_off],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 3);
            const cfg = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 1000, repChange: 0};
            const actions = [
                (cb) => device.bind('genOnOff', coordinator, cb),
                (cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg, cb),
            ];

            execute(device, actions, callback);
        },
    },`

I know that a pull request should be used but I could not figure out and still felt like trying to contribute. 

Last but not least zigbee2mqtt hass.io addon is great!

**Comment by Koenkk** [comment]
Hi!

Can you provide a link to this device?

**Comment by duesseldorferjung** [comment]
https://vetaar-anchor.com/Anchor_Project/helpmanual.jsp

Your efforts made it all the way to India :)

**Comment by duesseldorferjung** [comment]
And the vendor is actually Vetaar not Votaar, there using a fancy logo so I misread it.

**Comment by Koenkk** [comment]
Thanks for your contribution, supported now :smile:

**Comment by duesseldorferjung** [comment]
Thanks for the quick implementation. How long will it take to be available in the Hass.io Plugin ?

**Comment by Koenkk** [comment]
@duesseldorferjung is already available in the edge version.

**Comment by duesseldorferjung** [comment]
After almost a year now I am trying to add Plug of the same type and getting an error
(TypeError: Cannot read property 'bind' of undefined
    at bind (/zigbee2mqtt-1.11.0/node_modules/zigbee-herdsman-converters/devices.js:21:24)
To add Osram+ for example works.

**Comment by Koenkk** [comment]
@duesseldorferjung please share your `database.db` when the device is paired.

**Comment by duesseldorferjung** [comment]
[database.zip](https://github.com/Koenkk/zigbee-herdsman-converters/files/4291606/database.zip)

How can you be so fast? :)

**Comment by Koenkk** [comment]
Should be fixed in the latest dev branch (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by duesseldorferjung** [comment]
I can confirm. Big thanks! And I which some corporates had quick developers like that....  As I am still learning github, I will try to figure out how to see when this gets implemented in the normal branch.

**Comment by Koenkk** [comment]
Will be available in zigbee2mqtt 1.12.0 (+- 1.5 weeks from now)
