### ISSUE TITLE
"Unknown zigbee publish cmdType undefined" error and crash since v9.0.0

### ISSUE THREAD

**Issue by g27radio** [Koenkk/zigbee-shepherd-converters#429]
I've been receiving the following error since v9.0.0:

```
zigbee2mqtt:info 5/6/2019, 9:16:09 PM Device incoming...
zigbee2mqtt:info 5/6/2019, 9:16:09 PM MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
zigbee2mqtt:info 5/6/2019, 9:16:20 PM Zigbee publish to device '0x7cb03eaa00a18bbd', undefined - undefined - undefined - {"manufSpec":0,"disDefaultRsp":0} - null
zigbee2mqtt:error 5/6/2019, 9:16:20 PM Unknown zigbee publish cmdType undefined

```

After the last message, zigbee2mqtt stops responding.

Here is the message I'm sending when I get the error:

zigbee2mqtt/0x7cb03eaa00a18bbd/set
```
{
  "brightness": 255,
  "color": {
    "r": 255,
    "g": 43,
    "b": 72
  }
}
```

Switching back to v8.1.5 causes the issue to go away.

**Comment by Koenkk** [comment]
Are you on the latest zigbee2qmtt dev branch?

**Comment by g27radio** [comment]
Apparently my docker image was a couple days old.  I just modified my script to always pull the lastest-dev image first and now it works.
