### ISSUE TITLE
add configuration for 3 bulbs and 1 wall switch

### ISSUE THREAD

**Issue by drbios** [Koenkk/zigbee-shepherd-converters#441]
hello i don't know how to submit this information so this is my 3 types bulb configuration and 1 wall plug switch 

in devices.js

   //LEEDARSON
    {
        zigbeeModel: ['LED_GU10_OWDT'],
        model: 'ZM350STW1TCF',
        vendor: 'LEEDARSON',
        description: 'LED PAR16 50 GU10 tunable white',
        extend: generic.light_onoff_brightness_colortemp,
    },
    {
        zigbeeModel: ['M350ST-W1R-01'],
        model: 'M350STW1',
        vendor: 'LEEDARSON',
        description: 'LED PAR16 50 GU10 tunable white',
        extend: generic.light_onoff_brightness,
    },
    {
        zigbeeModel: ['ZHA-DimmableLight'],
        model: 'A806S-Q1R',
        vendor: 'LEEDARSON',
        description: 'LED E27 tunable white',
        extend: generic.light_onoff_brightness,
    },

// CLIMAX
    {
        zigbeeModel: ['PSM_00.00.00.35TC'],
        model: 'PSM-29ZBSR',
        vendor: 'Climax',
        description: 'Power plug',
        supports: 'on/off',
        fromZigbee: [fz.state_report,fz.state_change],
        toZigbee: [tz.on_off],
    },

homeasistat extension

    'PSM-29ZBSR': [configurations.switch],
    'ZM350STW1TCF': [configurations.light_brightness_colortemp],
    'M350STW1': [configurations.light_brightness],
    'A806S-Q1R': [configurations.light_brightness],

all working perfect
best regards

**Comment by Koenkk** [comment]
Thanks, all supported in the zigbee2mqtt dev branch now!
