### ISSUE TITLE
NYCE NCZ-3041-HA support 

### ISSUE THREAD

**Issue by jiki974** [Koenkk/zigbee-shepherd-converters#449]
In devices.js   NYCE 3043 exist, I have a NYCE 3041 and it's pretty the same except that it's a wall mounted motion sensor, so it's pretty simple to add it.

**Comment by Koenkk** [comment]
Did you check that it works?

**Comment by jiki974** [comment]
Yes that works and on their website http://nycesensors.com/support/ the wall mounted sensor and ceiling sensor have the same smarthings driver :

manufacturer: "NYCE", model: "3041", deviceJoinName: "NYCE Motion Sensor with T/H"
manufacturer: "NYCE", model: "3043", deviceJoinName: "NYCE Ceiling Motion Sensor with T/H"
manufacturer: "NYCE", model: "3045", deviceJoinName: "NYCE Curtain Motion Sensor with T/H"

**Comment by Koenkk** [comment]
Good! support in the dev branch now.
