### ISSUE TITLE
Adding Support for Heiman HS2WD Flash Siren

### ISSUE THREAD

**Issue by mccoy88f** [Koenkk/zigbee-shepherd-converters#461]
Hi to all.
I have this zigbee siren from heiman with id 'WarningDevice'
(http://www.heimantech.com/product/153.html)
Previously using Smartthing and adding it as generic siren or switch i can switch it on and off.
Someone can help me?
I can send log and everything needed!
Thanks a lot

**Comment by Koenkk** [comment]
Is this device working with https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js#L3121?

**Comment by mccoy88f** [comment]
I remove that device (i create It but don't work)

**Comment by Koenkk** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/1416 can help

**Comment by JLFN** [comment]
Support added https://github.com/Koenkk/zigbee-shepherd-converters/commit/574eb585edc148547630774159f52bfffac75a1b

**Comment by Koenkk** [comment]
@JLFN thanks, will close this.
