### ISSUE TITLE
Add support for Hue white ambiance Aurelle rectangle panel light LTC014

### ISSUE THREAD

**Issue by MrLee99** [Koenkk/zigbee-shepherd-converters#473]
Hi!

Sorry but I´ve no clue to add a PR...so here the manual way:

Please add above light according to:
`    {
        zigbeeModel: ['LTC014'],
        model: '3216231P5',
        vendor: 'Philips',
        description: 'Hue white ambiance Aurelle rectangle panel light',
        extend: hue.light_onoff_brightness_colortemp,
},`

Tried it and it´s working

Thanks a lot 
Mr.Lee / Christian

**Comment by Koenkk** [comment]
Added it, will be supported by zigbee2mqtt soon, thanks!
