### ISSUE TITLE
problem to pair xiaomi sensors

### ISSUE THREAD

**Issue by str3000** [Koenkk/zigbee-shepherd-converters#474]
Hallo,
ich komme nun selbst nicht mehr weiter. Koppeln meiner Xiaomi Window switches funktioniert (teilweise) nicht mehr. Habe 3 Sensoren die anscheinend zwar gepaired werden, jedoch wird kein "'model' angezeigt und sie funktionieren dann auch nicht.
Ich hatte mal ein Update von zigbee2mqtt gemacht und dann noch mal aktualisiert.
Weiss jemand was da los ist und wie man das beheben kann?
Hier ein Ausschnitt aus dem Logfile (mit einem Error):
{"ieeeAddr":"0x00158d000309ec9d","type":"EndDevice","model":"MCCGQ11LM","friendly_name":"0x00158d000309ec9d"},{"ieeeAddr":"0x00158d0002e9d718","type":"EndDevice","friendly_name":"0x00158d0002e9d718"},{"ieeeAddr":"0x00158d000309f063","type":"EndDevice","model":"MCCGQ11LM","friendly_name":"0x00158d000309f063"},{"ieeeAddr":"0x00158d000309be8b","type":"EndDevice","friendly_name":"0x00158d000309be8b"}]}'
6/3/2019, 6:31:13 PM - error: Failed to find device with ieeAddr: 'bridge/config/devices'
6/3/2019, 6:31:13 PM - warn: Cannot handle MQTT message on 'zigbee2mqtt/bridge/config/devices/get' with data '1559586673852'
6/3/2019, 6:31:13 PM - warn: Cannot handle MQTT message on 'zigbee2mqtt/bridge/config/groups' with data '1559586673873'
6/3/2019, 6:31:15 PM - info: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00158d0002e23a38","type":"EndDevice","model":"RTCGQ11LM","friendly_name":"0x00158d0002e23a38"},{"ieeeAddr":"0x00158d0002c7b761","type":"EndDevice","model":"MCCGQ11LM","friendly_name":"0x00158d0002c7b761"},{"ieeeAddr":"0x00158d0002c7b777","type":"EndDevice","model":"MCCGQ11LM","friendly_name":"0x00158d0002c7b777"},{"ieeeAddr":"0x00158d0002c7b734","type":"EndDevice","model":"MCCGQ11LM","friendly_name":"0x00158d0002c7b734"},{"ieeeAddr":"0x00158d0002bfdc35","type":"EndDevice","model":"MCCGQ11LM","friendly_name":"0x00158d0002bfdc35"},{"ieeeAddr":"0x00158d00025f1dcb","type":"EndDevice","model":"WSDCGQ11LM","friendly_name":"0x00158d00025f1dcb"},{"ieeeAddr":"0x00158d0002ea1dc6","type":"EndDevice","friendly_name":"0x00158d0002ea1dc6"},{"ieeeAddr":"0x84182600000d251f","type":"Router","model":"AB3257001NJ","friendly_name":"0x84182600000d251f"},{"ieeeAddr":"0x84182600000a47de","type":"Router","model":"AB3257001NJ","friendly_name":"0x84182600000a47de"},

**Comment by arteck** [comment]
du kommst aus dem iobroker .. das hat hier nix zu suchen

---------------------------------

you problem is from iobroker .. this works fine for me

**Comment by str3000** [comment]
ich verwende Redmatic.

es handelt sich aber um ein Problem mit zigbee2mqtt. wo wäre die richtige Stelle für den Bug zu melden?

**Comment by str3000** [comment]
was an update problem of zigbee2mqtt
