### ISSUE TITLE
old aqara button

### ISSUE THREAD

**Issue by arteck** [Koenkk/zigbee-shepherd-converters#475]
i have a error on line
https://github.com/Koenkk/zigbee-shepherd-converters/blob/bcf58c15120508bf9de33f89206c81c10a86582f/converters/fromZigbee.js#L423
when options.long_timeout is null or not available

i think options.long_timeout is not for all xiaomi devices

**Comment by Koenkk** [comment]
`options` should never be null, so if `options.long_timeout` is null it will take `1000`. What's the problem?

**Comment by arteck** [comment]
![grafik](https://user-images.githubusercontent.com/6681528/59176404-3770cb80-8b59-11e9-8c5f-5908aa493508.png)

here its undefined

**Comment by Koenkk** [comment]
IOBroker should at least always pass a empty object, @kirovilya can you fix this?

**Comment by kirovilya** [comment]
@Koenkk @arteck ok, I'll try

**Comment by kirovilya** [comment]
@arteck Check out version from github

**Comment by arteck** [comment]
@kirovilya thx
