### ISSUE TITLE
Commit E1603 and E1702 are the same 1aab849 breaks Home Assistant integration 

### ISSUE THREAD

**Issue by MarMed** [Koenkk/zigbee-shepherd-converters#476]
1aab849b593c95b6ac95b9b40376f5163ea384ed breaks Home Assistant integration with TRADFRI control outlet, with the current change:

`model: 'E1603/E1702',` 
in home assistant outlets turn unavailable.
reverting the change back:
`model: 'E1603',` 
In Home Assistant outlets function as expected.

**Comment by Koenkk** [comment]
Thanks, fixed!
