### ISSUE TITLE
Heiman Smoke detectors remote mute

### ISSUE THREAD

**Issue by odx** [Koenkk/zigbee-shepherd-converters#478]
The Heiman website states a feature named "APP remote mute" for their HS1SA / HS3SA smart smoke sensors. The "how to support new devices" article on zigbee2mqtt.io explains how to implement the "fromZigbee" messages that are triggered by the device. How can one find the message format for the "toZigbee" messages?

**Comment by Koenkk** [comment]
Most of the times, https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/toZigbee.js can be used as a reference.

To implement this specific command you need to know what to send, which can be accomplished via:
- Sniffing the traffic when sending it via the original gateway
- Hoping it uses a default command from: https://www.nxp.com/docs/en/user-guide/JN-UG-3115.pdf

If you know what to send, I can help in adding it to `toZigbee.js`.

**Comment by odx** [comment]
From what I understand from toZigbee.js it looks like the sensors use the IAS Zone Cluster (Chapter 37 in the referenced document). I assume that the attribute I am looking for is "u8CurrentZoneSensitivityLevel" (referenced on page 783). Also in the documentation it says "Push the button to lower the sensitivity" which results in muting the alarm.

As I don't have the gateway sniffing the traffic is currently not an option for me. How would this attribute be set through toZigbee.js?

Fortunately I have a broken sensor here that instantly goes into alarm state when I insert the battery. this is an ideal test object.

**Comment by Koenkk** [comment]
Something like

```js
sensitivity: {
        key: ['sensitivity'],
        convert: (key, value, message, type, postfix) => {
            const cid = 'ssIasZone';

            if (type === 'set') {
                return [{
                    cid: cid,
                    cmd: 'write',
                    cmdType: 'foundation',
                    zclData: [{
                        attrId: 19, // presentValue
                        dataType: 32, // dataType
                        attrData: 0,
                    }],
                    cfg: cfg.default,
                }];
            }
        },
    },
```

should do it, please try different values for `attrData` (0 - 5)

**Comment by odx** [comment]
I am currently setting up a development network so I can start tinkering. But I have another question beforehand:

Since the value is omitted in this code the value in the JSON is arbitrary?
Something like this should set the hard coded sensitivity, right?
```
{ "sensitivity":"foo" }
```

We could make the attrData variable by changing 
```
attrData: 0,
```
to
```
attrData: value,
```

In this case do you think a type check for integer should be added?

**Comment by Koenkk** [comment]
@odx yes, in that cause type checking should be added

**Comment by odx** [comment]
Nevertheless this attribute seems not to be the correct one.... Although receiving the smoke -> true message also in muted mode is normal, but none of the commands listed below did mute the beep...

```
  zigbee2mqtt:info 2019-6-24 9:38:11 PM Zigbee publish to device '0x00158d0002758987', ssIasZone - write - [{"attrId":19,"dataType":32,"attrData":1}] - {"manufSpec":0,"disDefaultRsp":0} - null
  zigbee2mqtt:info 2019-6-24 9:38:14 PM MQTT publish: topic 'zigbeedev/smoketest', payload '{"smoke":true,"battery_low":false,"linkquality":99}'
  zigbee2mqtt:info 2019-6-24 9:38:17 PM MQTT publish: topic 'zigbeedev/smoketest', payload '{"smoke":true,"battery_low":false,"linkquality":102}'
  zigbee2mqtt:info 2019-6-24 9:38:20 PM MQTT publish: topic 'zigbeedev/smoketest', payload '{"smoke":true,"battery_low":false,"linkquality":99}'
  zigbee2mqtt:info 2019-6-24 9:38:22 PM Zigbee publish to device '0x00158d0002758987', ssIasZone - write - [{"attrId":19,"dataType":32,"attrData":2}] - {"manufSpec":0,"disDefaultRsp":0} - null
  zigbee2mqtt:info 2019-6-24 9:38:27 PM Zigbee publish to device '0x00158d0002758987', ssIasZone - write - [{"attrId":19,"dataType":32,"attrData":3}] - {"manufSpec":0,"disDefaultRsp":0} - null
  zigbee2mqtt:info 2019-6-24 9:38:31 PM Zigbee publish to device '0x00158d0002758987', ssIasZone - write - [{"attrId":19,"dataType":32,"attrData":4}] - {"manufSpec":0,"disDefaultRsp":0} - null
  zigbee2mqtt:info 2019-6-24 9:38:34 PM MQTT publish: topic 'zigbeedev/smoketest', payload '{"smoke":true,"battery_low":false,"linkquality":97}'
  zigbee2mqtt:info 2019-6-24 9:38:37 PM Zigbee publish to device '0x00158d0002758987', ssIasZone - write - [{"attrId":19,"dataType":32,"attrData":5}] - {"manufSpec":0,"disDefaultRsp":0} - null
  zigbee2mqtt:info 2019-6-24 9:38:37 PM MQTT publish: topic 'zigbeedev/smoketest', payload '{"smoke":true,"battery_low":false,"linkquality":99}'
  zigbee2mqtt:info 2019-6-24 9:38:40 PM Zigbee publish to device '0x00158d0002758987', ssIasZone - write - [{"attrId":19,"dataType":32,"attrData":0}] - {"manufSpec":0,"disDefaultRsp":0} - null
  zigbee2mqtt:info 2019-6-24 9:38:40 PM MQTT publish: topic 'zigbeedev/smoketest', payload '{"smoke":true,"battery_low":false,"linkquality":97}'
```

**Comment by Koenkk** [comment]
I'm not sure how to continue, we need to find out what to send, perhaps somebody else can sniff the traffic with the original gateway.

**Comment by odx** [comment]
I am considering getting a base to resolve this as one of my sensors is mounted at a high ceiling and is barely reachable.

Unfortunately there are at least three different models of the gateway available and I am struggling in understanding if they are all interoperable.

**Comment by odx** [comment]
I have purchased a Ferguson smart hub which is identical to the heiman gateway. I expect to get it on Monday.
In the meantime I am setting up the sniffing tools but got stuck on linking whsniff with Wireshark. I followed the (ubuntu) guide of your [tutorial](https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html) but when Wireshark starts up I get the following error: "Unrecognized libcap format or not libcap data." From what I found on the internet whsniff outputs pcap data which can be processed by Wireshark. But do I need to specify this somehow explicitly?

**Comment by odx** [comment]
OK... it boils down to whsniff not beeing able to connect to the CC2531 although it is called with sudo:
```
sudo whsniff -c 11
ERROR: Could not open CC2531 USB Dongle with sniffer firmware. Not found or not accessible.
```
I flashed the sniffer firmware from zboss. Is it correct that the firmware is only 24KB in size?

**Comment by Koenkk** [comment]
I would suggest installing the packet sniffer firmware. 24kb is indeed small

**Comment by odx** [comment]
That firmware works. Thanks.

**Comment by JLFN** [comment]
> That firmware works. Thanks.

Can you please try to sniff then try to change other settings like sensitivity when you have this sorted.

**Comment by odx** [comment]
After installing the hub I could not manage to mute the sensor remotely. The alarm can only be muted locally in the app. Even the hubs alarm is not stopped through the app.
Unless this is no bug of the system I assume that it is not possible to mute the alarm through Zigbee. I will clarify this with the hub manufacturer.

**Comment by timesout404** [comment]
are you guys able to make the mute happen through zigbee2mqtt ?

![image](https://user-images.githubusercontent.com/83847185/167311098-75a592d0-4686-48fa-9c8f-aa84dbd5cf53.png)


![image](https://user-images.githubusercontent.com/83847185/167311078-ebac4ff1-e578-4174-a8ba-2f05e915042f.png)

**Comment by jancoow** [comment]
I'm also looking forward to this. This is one key point for me of buying this sensor.

**Comment by NgocHoang2017** [comment]
Hi everyone Have you looking this problem (remote mute)

**Comment by odx** [comment]
According to my earlier message I assume there is no remote mute command that can be issued via zigbee. The mute function only affects the alarm inside the app and is a “local” mute on the smart phone only.

The sensor’s and hub’s alarm keep beeping when you mute it in the app in the setup with the original manufacturer’s hardware.
