### ISSUE TITLE
Xiaomi Aqara Flora 

### ISSUE THREAD

**Issue by aleszuin** [Koenkk/zigbee-shepherd-converters#480]
Hi is there someone working on Xioami/Aqara flower /plan monitor ? Seems to be a good and cheap device to monitor plant condition, especially when you out from home.

https://it.aliexpress.com/item/Xiao-mi-mi-flora-monitor-Digitale-Piante-Da-Giardino-Erba-Fiore-Cura-Di-Acqua-del-Suolo/33030540350.html

HomeAssistant integrate it but i'd like to bridge all my Zigbee to the same Gateway and through mqtt is a more flexible solution.  Thanks

**Comment by Koenkk** [comment]
This is a bluetooth device and therefore not supported by zigbee2mqtt. 

Personally I also have it and use it together with an ESP32 + esphome.
