### ISSUE TITLE
Latest version of zcl-packet

### ISSUE THREAD

**Issue by ptvoinfo** [Koenkk/zigbee-shepherd-converters#495]
@Koenkk 
Could you please consider a possibility of adding a package dependency to the latest version of zcl-packet (your fork). 

I'm interested in the "onWithTimedOff" command, but that bugfix released later.

**Comment by Koenkk** [comment]
Done, I moved zigbee-shepherd-converters to zigbee-herdsman (https://github.com/koenkk/zigbee-herdsman) which contains zcl-packet and zcl-id.
