### ISSUE TITLE
Add Support for Device 'TRADFRI bulb E27 CWS opal 600lm'

### ISSUE THREAD

**Issue by MarcE85** [Koenkk/zigbee-shepherd-converters#503]
Hey,

please add Support for Device: 'TRADFRI bulb E14 CWS opal 600lm'

Regards Marc

**Comment by Koenkk** [comment]
This device is already supported: https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js#L526

**Comment by MarcE85** [comment]
Sorry, i was wrong. The Device is: 

TRADFRI bulb E**14** CWS opal 600lm.

Regards Marc

**Comment by Koenkk** [comment]
Is this the bulb https://www.ikea.com/gb/en/p/tradfri-led-bulb-e14-600-lumen-wireless-dimmable-white-spectrum-opal-white-80408585/ ?

**Comment by MarcE85** [comment]
> Is this the bulb https://www.ikea.com/gb/en/p/tradfri-led-bulb-e14-600-lumen-wireless-dimmable-white-spectrum-opal-white-80408585/ ?

No its not. It's exactly like [https://www.ikea.com/de/de/p/tradfri-led-leuchtmittel-e27-600-lm-kabellos-dimmbar-farb-und-weissspektrum-opalweiss-00408612/](url) but as E14 Version :)

i couldn't find the bulb on theyr website.

Regards Marc

**Comment by Koenkk** [comment]
Could you share your `data/database.db` file?

**Comment by Gesfenlir** [comment]
Hi,

Just bought the same Ikea bulb and got the following in logs:
`warn: Device with modelID 'TRADFRI bulb E14 CWS opal 600lm' is not supported.`

Model reference: LED1624G9

Here the database entry for it.
`{"id":25,"type":"Router","ieeeAddr":"0x000d6ffffe32593a","nwkAddr":9020,"manufId":4476,"epList":[1],"status":"online","joinTime":1564656550,"endpoints":{"1":{"profId":49246,"epId":1,"devId":512,"inClusterList":[0,3,4,5,6,8,768,2821,4096],"outClusterList":[5,25,32,4096],"clusters":{}}},"_id"":"CvZ7skrxbbMUBHkK"}`

**Comment by Koenkk** [comment]
@Gesfenlir that device is already supported, https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js#L544 (update to latest zigbee2mqtt dev to use it).

**Comment by Gesfenlir** [comment]
Thanks!
Worked well... hqd to force "-f" the checkout to dev.
