### ISSUE TITLE
Incorrect color conversion in utils.js

### ISSUE THREAD

**Issue by Cortronic** [Koenkk/zigbee-shepherd-converters#510]
Hi Koen,

The red, green and blue values in the function rgbToXY() in utils.js need to be scaled to values between 0.0 and 1.0 before applying the gamma correction.
This can be simpele done by devide all color values by 255.

For more info see:
https://github.com/mikz/PhilipsHueSDKiOS/blob/master/ApplicationDesignNotes/RGB%20to%20xy%20Color%20conversion.md

Regards Cor

**Comment by Koenkk** [comment]
Could you make a PR to fix the conversion?
