### ISSUE TITLE
HS3SA Battery Percentage Remaining

### ISSUE THREAD

**Issue by odx** [Koenkk/zigbee-shepherd-converters#511]
In my sniffing attempts (#478) I noticed that the sensor reports the battery percentage. I found that the devices.js only specifies the "heiman_smoke" attribute in "fromZigbee". For the HS1SA there are also the attribute reports implemented including the battery percentage with the normalized percentage (the device reports just as the HS1SA 200 for 100%). What I could not identify is the battery alarm state in that attribute report. Since it is already included in the "heiman_smoke", I believe that heiman has moved this alarm flag there with the HS3SA.

As the alarm flag is missing in the reports of the HS3SA the "battery_200" attribute can not be directly enabled for this device. Is this assumption correct? I attached a screenshot of the cluster library frame from the Wireshark sniff.
<img width="572" alt="Bildschirmfoto 2019-07-08 um 22 34 53" src="https://user-images.githubusercontent.com/65194/60840858-b39a1580-a1d0-11e9-8e9a-3d8c6f48d965.png">

**Comment by Koenkk** [comment]
This is the same as the HS1SA (`fz.battery_200`), I would expect that you currently see a `No converter available...` log message when the HS3SA sends this message.

**Comment by odx** [comment]
I will have a look on it. Due to the coordinator problem I had, the old log files are flushed and I need to wait for battery reports from the sensors...

**Comment by odx** [comment]
@Koenkk something like this?

```
7/13/2019, 3:53:34 PM - warn: No converter available for 'HS3SA' with cid 'genBasic', type 'devChange' and data '{"cid":"genBasic","data":{"manufacturerName":"HEIMAN","modelId":"SmokeSensor-N","powerSource":3}}'
```

**Comment by odx** [comment]
After some time of observation, I could not find such log entries that point to that reporting.

Also I tried to sniff the complete sequence including pairing and testing the smoke sensor without being able reproduce this message again. (Battery Level is displayed as 0% in manufacturers mobile app. So I expect it actually never has been sent for this sensor)

Either the two sensors I use have a different hardware / software or the reporting only takes place in specific circumstances (which I could not figure out so far...)

Any ideas how we can figure this out?

**Comment by Koenkk** [comment]
The current configuration doesn't seem to setup battery reporting.

Please try with the following:
```js
{
    zigbeeModel: ['SmokeSensor-N'],
    model: 'HS3SA',
    vendor: 'HEIMAN',
    description: 'Smoke detector',
    supports: 'smoke',
    fromZigbee: [fz.heiman_smoke, fz.battery_200],
    toZigbee: [],
    configure: (ieeeAddr, shepherd, coordinator, callback) => {
        const device = shepherd.find(ieeeAddr, 1);
        const actions = [
            (cb) => device.write('ssIasZone', 'iasCieAddr', coordinator.device.getIeeeAddr(), cb),
            (cb) => device.functional('ssIasZone', 'enrollRsp', {enrollrspcode: 0, zoneid: 23}, cb),
            (cb) => device.bind('genPowerCfg', coordinator, cb),
            // Time is in seconds. 65535 means no report. 65534 is max value: 18 hours, 12 minutes 14 seconds.
            (cb) => device.report('genPowerCfg', 'batteryPercentageRemaining', 0, 3, 0, cb),
            (cb) => device.report('genPowerCfg', 'batteryAlarmState', 1, 3, 1, cb),
        ];

        execute(device, actions, callback, 1000);
    },
},
```

After this you will probably spammed by battery reports, we will fix this later.

Note that after this change you should a `Succesfuly configured...` message for this device in your zigbee2mqtt startup log. If you see a failed, restart zigbee2mqtt and while doing this press buttons on the device to keep it awake.

**Comment by odx** [comment]
yes. after keeping the device awake during start up (I was pressing the network button every few seconds) it seems to be working.
But the converter is not present yet...

```
  zigbee2mqtt:warn 8/3/2019, 7:28:28 PM Failed to configure smoke_wz (0x00158d0002758682) ('invalidValue') (attempt #1)
  zigbee2mqtt:warn 8/3/2019, 7:28:28 PM This can be ignored if the device is working properly
  zigbee2mqtt:warn 8/3/2019, 7:28:34 PM No converter available for 'HS3SA' with cid 'genPowerCfg', type 'attReport' and data '{"cid":"genPowerCfg","data":{"batteryPercentageRemaining":200}}'
  zigbee2mqtt:warn 8/3/2019, 7:28:34 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
  zigbee2mqtt:warn 8/3/2019, 7:28:34 PM No converter available for 'HS3SA' with cid 'genPowerCfg', type 'devChange' and data '{"cid":"genPowerCfg","data":{"batteryPercentageRemaining":200}}'
  zigbee2mqtt:warn 8/3/2019, 7:28:34 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
  zigbee2mqtt:warn 8/3/2019, 7:28:38 PM No converter available for 'HS3SA' with cid 'genPowerCfg', type 'attReport' and data '{"cid":"genPowerCfg","data":{"batteryPercentageRemaining":200}}'
  zigbee2mqtt:warn 8/3/2019, 7:28:38 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
  zigbee2mqtt:warn 8/3/2019, 7:28:41 PM No converter available for 'HS3SA' with cid 'genPowerCfg', type 'attReport' and data '{"cid":"genPowerCfg","data":{"batteryPercentageRemaining":200}}'
  zigbee2mqtt:warn 8/3/2019, 7:28:41 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
   zigbee2mqtt:warn 8/3/2019, 7:28:44 PM No converter available for 'HS3SA' with cid 'genPowerCfg', type 'attReport' and data '{"cid":"genPowerCfg","data":{"batteryPercentageRemaining":200}}'
  zigbee2mqtt:warn 8/3/2019, 7:28:44 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
  zigbee2mqtt:warn 8/3/2019, 7:28:48 PM Failed to configure smoke_sz (0x00158d0002754836) ('Error: AF data request fails, status code: 183. APS no ack.') (attempt #1)
  zigbee2mqtt:warn 8/3/2019, 7:28:48 PM This can be ignored if the device is working properly
  zigbee2mqtt:warn 8/3/2019, 7:28:48 PM No converter available for 'HS3SA' with cid 'genPowerCfg', type 'attReport' and data '{"cid":"genPowerCfg","data":{"batteryPercentageRemaining":200}}'
  zigbee2mqtt:warn 8/3/2019, 7:28:48 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
  zigbee2mqtt:info 8/3/2019, 7:28:48 PM MQTT publish: topic 'zigbee/fenster_abstellraum', payload '{"contact":true,"linkquality":73,"battery":100,"voltage":3025,"last_seen":"2019-08-03T19:28:48.382Z"}'
  zigbee2mqtt:warn 8/3/2019, 7:28:51 PM No converter available for 'HS3SA' with cid 'genPowerCfg', type 'attReport' and data '{"cid":"genPowerCfg","data":{"batteryPercentageRemaining":200}}'
  zigbee2mqtt:warn 8/3/2019, 7:28:51 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
```

**Comment by odx** [comment]
The second time I started zigbee2mqtt I get the following message regarding the configuration:
```
zigbee2mqtt:warn 8/3/2019, 7:37:19 PM Failed to configure smoke_wz (0x00158d0002758682) ('unsupAttribute') (attempt #1)
```

**Comment by odx** [comment]
As you see in the log the reporting was configured to send the message every 3 seconds. I changed it to 3600 seconds in the configuration but for that sensor it was set to 23 seconds. Also if I adapt the 65534 from the HS1SA it reports the battery state every 23 seconds. (Device was kept away during zigbee2mqtt startup).

For another sensor that has never been configured to report in the 3 second interval it looks like it worked. I got a single message and no more so far.

**Comment by Koenkk** [comment]
ok great, I've added this configuration now and this will be added in the next release, if you still see the messages every 3 seconds I would suggest to re-pair the device. 

Please close if this issue has been solved.

**Comment by odx** [comment]
Well the data comes in... But I can't get the battery reporting interval beyond 23 seconds...

I have a variety of errors during configuration:
```
8/3/2019, 7:28:28 PM Failed to configure smoke_wz (0x00158d0002758682) ('invalidValue') (attempt #1)
```
or
```
8/3/2019, 7:37:19 PM Failed to configure smoke_wz (0x00158d0002758682) ('unsupAttribute') (attempt #1)
```
or
```
8/5/2019, 6:39:49 PM - warn: Failed to configure 0x00158d0002758682 (0x00158d0002758682) ('Error: AF data request fails, status code: 240. MAC transaction expired.') (attempt #3)
```

**Comment by Koenkk** [comment]
After changing the configuration, did you repair it?


You will probably see `240. MAC transaction expired` because the device is sleeping, you can wake it up by pressing buttons on it.

**Comment by odx** [comment]
I ended up relying solely on the "repair" way as it is unpractical to restart zigbee2mqtt every time and keep the devices awake. If I read the logs correctly the configuration for attribute reporting is performed for one device after another. With a 10000ms timeout this takes quite a while when you have all of the devices asleep. Therefore I have to keep pressing the button on the device for minutes in order to keep it awake.

Here is a log that shows the complete pairing process including two attempts to configure it (although it states attempt #2 and #3. The first one does not show up in the log at all):

```
8/5/2019, 6:39:29 PM - info: New device 'SmokeSensor-N' with address 0x00158d0002758682 connected!
8/5/2019, 6:39:29 PM - info: MQTT publish: topic 'zigbee/bridge/log', payload '{"type":"device_connected","message":"0x00158d0002758682","meta":{"modelID":"SmokeSensor-N"}}'
8/5/2019, 6:39:30 PM - warn: No converter available for 'HS3SA' with cid 'genBasic', type 'devChange' and data '{"cid":"genBasic","data":{"manufacturerName":"HEIMAN","modelId":"SmokeSensor-N","powerSource":3}}'
8/5/2019, 6:39:30 PM - warn: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
8/5/2019, 6:39:34 PM - info: Device incoming...
8/5/2019, 6:39:34 PM - info: MQTT publish: topic 'zigbee/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
8/5/2019, 6:39:36 PM - info: MQTT publish: topic 'zigbee/0x00158d0002758682', payload '{"battery":100,"linkquality":78,"last_seen":"2019-08-05T18:39:36.532Z"}'
8/5/2019, 6:39:36 PM - warn: No converter available for 'HS3SA' with cid 'genPowerCfg', type 'devChange' and data '{"cid":"genPowerCfg","data":{"batteryPercentageRemaining":200}}'
8/5/2019, 6:39:36 PM - warn: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
8/5/2019, 6:39:37 PM - warn: Failed to configure 0x00158d0002758682 (0x00158d0002758682) ('unsupAttribute') (attempt #2)
8/5/2019, 6:39:37 PM - warn: This can be ignored if the device is working properly
8/5/2019, 6:39:38 PM - info: MQTT publish: topic 'zigbee/0x00158d0002758682', payload '{"battery":100,"linkquality":76,"last_seen":"2019-08-05T18:39:38.248Z","elapsed":1716}'
8/5/2019, 6:39:49 PM - warn: Failed to configure 0x00158d0002758682 (0x00158d0002758682) ('Error: AF data request fails, status code: 240. MAC transaction expired.') (attempt #3)
8/5/2019, 6:39:49 PM - warn: This can be ignored if the device is working properly
```

**Comment by Koenkk** [comment]
Instead of use the repair up-on start, I would recommend removing all entries of `0x00158d0002758682` from database.db, restart zigbee2mqtt and re-pair the device. On pair it will also execute the configure section (immediately).

**Comment by odx** [comment]
Purging all entries from the database.db has the very same result. First error is "unsupAttribute" second error is Timeout...

The sensor still sends the battery status every 23 seconds.

```
8/8/2019, 6:57:23 PM - info: Zigbee: allowing new devices to join.
8/8/2019, 6:57:23 PM - info: MQTT publish: topic 'zigbee/bridge/config', payload '{"version":"1.5.1","commit":"ac3b924","coordinator":20190619,"log_level":"info","permit_join":true}'
8/8/2019, 6:57:37 PM - info: Device incoming...
8/8/2019, 6:57:37 PM - info: MQTT publish: topic 'zigbee/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
8/8/2019, 6:57:40 PM - info: MQTT publish: topic 'zigbee/smoke_wz', payload '{"battery":100,"linkquality":65,"last_seen":"2019-08-08T18:57:40.929Z"}'
8/8/2019, 6:57:40 PM - warn: No converter available for 'HS3SA' with cid 'genPowerCfg', type 'devChange' and data '{"cid":"genPowerCfg","data":{"batteryPercentageRemaining":200}}'
8/8/2019, 6:57:40 PM - warn: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
8/8/2019, 6:57:42 PM - warn: Failed to configure smoke_wz (0x00158d0002758682) ('unsupAttribute') (attempt #1)
8/8/2019, 6:57:42 PM - warn: This can be ignored if the device is working properly
8/8/2019, 6:57:42 PM - info: MQTT publish: topic 'zigbee/smoke_wz', payload '{"battery":100,"linkquality":57,"last_seen":"2019-08-08T18:57:42.653Z","elapsed":1724}'
8/8/2019, 6:58:05 PM - warn: Failed to configure smoke_wz (0x00158d0002758682) ('Error: AF data request fails, status code: 183. APS no ack.') (attempt #2)
8/8/2019, 6:58:05 PM - warn: This can be ignored if the device is working properly
8/8/2019, 6:58:10 PM - info: MQTT publish: topic 'zigbee/smoke_wz', payload '{"battery":100,"linkquality":60,"last_seen":"2019-08-08T18:58:10.535Z","elapsed":27882}'
8/8/2019, 6:58:29 PM - warn: Failed to configure smoke_wz (0x00158d0002758682) ('Error: AF data request fails, status code: 183. APS no ack.') (attempt #3)
8/8/2019, 6:58:29 PM - warn: This can be ignored if the device is working properly
8/8/2019, 6:58:33 PM - info: MQTT publish: topic 'zigbee/smoke_wz', payload '{"battery":100,"linkquality":60,"last_seen":"2019-08-08T18:58:33.873Z","elapsed":23338}'
8/8/2019, 6:58:57 PM - info: MQTT publish: topic 'zigbee/smoke_wz', payload '{"battery":100,"linkquality":63,"last_seen":"2019-08-08T18:58:57.330Z","elapsed":23457}'
```

**Comment by odx** [comment]
What is the typical behavior of such devices? Could the 23 seconds be the manufacturer defined maximum reporting interval? Will this (IMHO short) interval drain the battery to much?

Any proposals on this?

**Comment by Koenkk** [comment]
@odx typically devices report according to the values, how did you got *For another sensor that has never been configured to report in the 3 second interval it looks like it worked. I got a single message and no more so far.* (https://github.com/Koenkk/zigbee-shepherd-converters/issues/511#issuecomment-517951470). If I understand it, it worked properly for this one?

**Comment by odx** [comment]
I thought it was working for the other sensor. But it doesn't. There is no report for this device since 3rd of August.

I tried a lot repairing the sensor now but I its hard to figure out a pattern. Sometimes no configuration is triggered at all (Device is already in network).

But allthough the sometimes configuration is attempted, it currently still fails:
```
zigbee2mqtt:warn 8/13/2019, 8:26:32 PM Failed to configure 0x00158d0002758682 (0x00158d0002758682) ('invalidValue') (attempt #2)
```

What exactly do "invalidValue" and "unsupAttribute" mean?

**Comment by odx** [comment]
I tried this report configuration:
```
(cb) => device.report('genPowerCfg', 'batteryPercentageRemaining', 10, 300, 0, cb),
```
And it seems to work. Allthough I still get the invalidValue message.
I will observe and try with other sensors. Maybe max report frequency (param 3?) cannot be 0...

**Comment by odx** [comment]
I spent some time playing around with the values. What turned out to work best for me is the following:

```
{
        zigbeeModel: ['SmokeSensor-N'],
        model: 'HS3SA',
        vendor: 'HEIMAN',
        description: 'Smoke detector',
        supports: 'smoke',
        fromZigbee: [fz.heiman_smoke, fz.battery_200, fz.ignore_power_change],
        toZigbee: [],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 1);
            const actions = [
                (cb) => device.write('ssIasZone', 'iasCieAddr', coordinator.device.getIeeeAddr(), cb),
                (cb) => device.functional('ssIasZone', 'enrollRsp', {enrollrspcode: 0, zoneid: 23}, cb),
                (cb) => device.bind('genPowerCfg', coordinator, cb),
                // Time is in seconds. 65535 means no report. 65534 is max value: 18 hours, 12 minutes 14 seconds. Allthough only 10 for max freq and less than 3600 for min freq worked for me.
                (cb) => device.report('genPowerCfg', 'batteryPercentageRemaining', 10, 3599, 0, cb),
                (cb) => device.report('genPowerCfg', 'batteryAlarmState', 10, 3599, 1, cb),
            ];
    
            execute(device, actions, callback, 1000);
        },
    },
```

Note: I additionally had to **add fz.ignore_power_change** as converter in order to avoid an error regarding unneeded reports.

I had to set the third parameter, which I assume to be "max reporting frequency" to **10** seconds. With 0 or 1 second I could not configure the devices correctly.

Any value for the minimum reporting interval greater or equal than 3600 seconds resulted in a configuration error: unsupAttribute. When this error message appears, the reporting does not take place.

When I have 10 for max reporting interval and **3599** (or less) as minimum reporting interval, I get the following error during configuration: invalidValue. Nevertheless the reporting works.

I was not able to set reporting intervals greater than 1 hour.

@Koenkk Those changes should be incorporated in the device configuration file for the next release.



Also, I am wondering if there is actually any difference between the HS1SA and the HS3SA and if the HS1SA configuration is indeed working.

By the way: what is the meaning for the parameter after 3599 in this configuration which is 0 for batteryPercentageRemaining and 1 for batteryAlarmState?

**Comment by Koenkk** [comment]
A last thing we could try is to use the api in a different way (looks hacky indeed, but I'm refactoring this part with the zigbee-herdsman refactor). This should set the reporting interval to +- 17 hours

```js
{
    zigbeeModel: ['SmokeSensor-N'],
    model: 'HS3SA',
    vendor: 'HEIMAN',
    description: 'Smoke detector',
    supports: 'smoke',
    fromZigbee: [fz.heiman_smoke, fz.battery_200, fz.ignore_power_change],
    toZigbee: [],
    configure: (ieeeAddr, shepherd, coordinator, callback) => {
        const device = shepherd.find(ieeeAddr, 1);
        const cfg = {
            direction: 0, attrId: 33, dataType: 32, minRepIntval: 10, maxRepIntval: repInterval.MAX, repChange: 0,
        };

        const actions = [
            (cb) => device.write('ssIasZone', 'iasCieAddr', coordinator.device.getIeeeAddr(), cb),
            (cb) => device.functional('ssIasZone', 'enrollRsp', {enrollrspcode: 0, zoneid: 23}, cb),
            (cb) => device.bind('genPowerCfg', coordinator, cb),
            (cb) => device.foundation('genPowerCfg', 'configReport', [cfg], foundationCfg, cb),
        ];

        execute(device, actions, callback, 1000);
    },
},
```

That parameter is the reportable change, you can read more about it here: file:///C:/Users/koen.kanters/Downloads/07-5123-06-zigbee-cluster-library-specification.pdf (2.5.7.1.7)

**Comment by odx** [comment]
Wow!

```
8/20/2019, 6:46:11 PM - info: New device 'SmokeSensor-N' with address 0x00158d0002758682 connected!
8/20/2019, 6:46:11 PM - info: MQTT publish: topic 'zigbee/bridge/log', payload '{"type":"device_connected","message":"0x00158d0002758682","meta":{"modelID":"SmokeSensor-N"}}'
8/20/2019, 6:46:11 PM - warn: Configuring 0x00158d0002758682 (0x00158d0002758682) ...
8/20/2019, 6:46:14 PM - info: Device incoming...
8/20/2019, 6:46:14 PM - info: MQTT publish: topic 'zigbee/bridge/log', payload '{"type":"pairing","message":"device incoming"}'
8/20/2019, 6:46:18 PM - info: Successfully configured 0x00158d0002758682 (0x00158d0002758682)
```

Looks promising. First time I saw a successful configuration process for those sensors. I will report if that actually worked tomorrow when the ±17 hours are over.

Well but with this new configuration there is no reporting for batteryAlarmState configured. Is it? Should we add this as well?

**Comment by odx** [comment]
Works!

```
{"smoke":false,"battery_low":false,"linkquality":94,"last_seen":"2019-08-21T12:25:25.591Z","battery":42.5,"elapsed":62771711}
```
17,43 hours.

**Comment by Koenkk** [comment]
Awesome! Could you make a PR?
