### ISSUE TITLE
Any downside for ignoring case for device model IDs?

### ISSUE THREAD

**Issue by qosmio** [Koenkk/zigbee-shepherd-converters#518]
I've had issues with a few OSRAM devices reporting their model ids with different cases than what is in the devices.js file.

For example:

I received the following error with a supported device. The OSRAM light strip.
```warn: Device with modelID 'FLEX RGBW' is not supported```

I had to change the casing of ```zigbeeModel: ['Flex RGBW']``` to ```zigbeeModel: ['FLEX RGBW']```

So was curious to know if casing can be ignored for devices, or would I need to create a pull request with the same model, but capitalized.

**Comment by Koenkk** [comment]
Nope, implemented, casing will be ignored now, thanks.
