### ISSUE TITLE
Add Zemismart 8W RGBW Bulb HGZB-BLC4-NO8A-E27

### ISSUE THREAD

**Issue by kvvoff** [Koenkk/zigbee-shepherd-converters#523]
Link to product: bit.ly/Zs8wLdBlb

I add to devices.js
`    {
        zigbeeModel: ['FNB56-ZCW25FB2.1'],
        model: 'HGZB-BLC4-NO8A-E27',
        vendor: 'Zemismart',
        description: 'Smart 8W E27 RGBW bulb',
        supports: 'ON/OFF, dimming, color temperature',
        extend: generic.light_onoff_brightness_colortemp_colorxy,
    },`

**Comment by kvvoff** [comment]
after adding this is what appeared in my database.db:

`{"id":4,"type":"Router","ieeeAddr":"0x00158d00025c9c05","nwkAddr":2054,"manufId":4478,"epList":[11],"status":"online","joinTime":1563386542,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25],"clusters":{}}},"_id":"OgaGpNyxZ2Lngr3K"}
{"id":4,"type":"Router","ieeeAddr":"0x00158d00025c9c05","nwkAddr":2054,"manufId":4478,"manufName":"Feibit","powerSource":"Mains (single phase)","modelId":"FNB56-ZCW25FB2.1","epList":[11],"status":"online","joinTime":1563386542,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25],"clusters":{}}},"_id":"OgaGpNyxZ2Lngr3K"}
{"id":4,"type":"Router","ieeeAddr":"0x00158d00025c9c05","nwkAddr":2054,"manufId":4478,"manufName":"Feibit","powerSource":"Mains (single phase)","modelId":"FNB56-ZCW25FB2.1","epList":[11],"zclVersion":2,"appVersion":1,"stackVersion":1,"hwVersion":1,"swBuildId":"V1.5","status":"online","joinTime":1563386542,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25],"clusters":{}}},"dateCode":"20171209","_id":"OgaGpNyxZ2Lngr3K"}
{"id":4,"type":"Router","ieeeAddr":"0x00158d00025c9c05","nwkAddr":2054,"manufId":4478,"manufName":"Feibit","powerSource":"Mains (single phase)","modelId":"FNB56-ZCW25FB2.1","epList":[11],"zclVersion":2,"appVersion":1,"stackVersion":1,"hwVersion":1,"swBuildId":"V1.5","status":"online","joinTime":1563386542,"endpoints":{"11":{"profId":49246,"epId":11,"devId":528,"inClusterList":[0,3,4,5,6,8,768,4096],"outClusterList":[25],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{}},"genIdentify":{"dir":{"value":1},"attrs":{}},"genGroups":{"dir":{"value":1},"attrs":{}},"genScenes":{"dir":{"value":1},"attrs":{}},"genOnOff":{"dir":{"value":1},"attrs":{}},"genLevelCtrl":{"dir":{"value":1},"attrs":{}},"genOta":{"dir":{"value":2},"attrs":{}},"lightingColorCtrl":{"dir":{"value":1},"attrs":{}},"lightLink":{"dir":{"value":1},"attrs":{}}}}},"dateCode":"20171209","_id":"OgaGpNyxZ2Lngr3K"}

**Comment by kvvoff** [comment]
or if i change in my database.db: 
**FNB56-ZCW25FB2.1** to already integrated **FNB56-ZCW25FB1.6** (https://www.zigbee2mqtt.io/devices/HGZB-06A) 

This installation also works.
and maybe it seems to me, but so the recall of light bulbs on teams is much faster

**Comment by Koenkk** [comment]
Added it, thanks!
