### ISSUE TITLE
Add support for device "Switch 1~6 gang"

### ISSUE THREAD

**Issue by GuGu927** [Koenkk/zigbee-shepherd-converters#539]
I'm very appreciate to your program.
Can you add my devices?

Here's my 3gang switch information. (Works well. Test completed for 1~6 gang)
Here's my db : https://pastebin.com/0V8m4fAQ
Here's my log : https://pastebin.com/c2aDs72c
Here's my debug: https://pastebin.com/0yMz71zh
Here's my custom devices.js : https://pastebin.com/4awi82YT
Here's my custom homeassistant.js : https://pastebin.com/NsnRhfGS
And I added postfixes.
/lib/util/utils.js   find  "bottom_" and add 'center_left',  'center_right' 

Here's device url
https://www.hej.life/shop/?idx=17
https://cdn.imweb.me/upload/S201901095c3581af7317d/7e2b3c21ea3d8.png

Model name
1gang : GLSK3ZB-1711
2gang : GLSK3ZB-1712
3gang : GLSK3ZB-1713
4gang : GLSK6ZB-1714
5gang : GLSK6ZB-1715
6gang : GLSK6ZB-1716

Thank you.

**Comment by Koenkk** [comment]
Please make a pull request

**Comment by GuGu927** [comment]
@Koenkk  Oh. I didn't know about that. I'll do that. Sorry. Thank you.
