### ISSUE TITLE
Iris Motion and temperature sensor error

### ISSUE THREAD

**Issue by stkang** [Koenkk/zigbee-shepherd-converters#542]
[sensor]
zigbeeModel: ['3326-L'],
model: '3326-L',
vendor: 'Iris',

[log]
 zigbee2mqtt:debug 7/27/2019, 11:16:17 AM Configuring 0x000d6f0010660529 (0x000d6f0010660529) ...
  zigbee-shepherd:request REQ --> AF:dataRequest, transId: 2 +7s
  zigbee-shepherd:request RSP <-- AF:dataRequest, status: 0 +11ms
  zigbee-shepherd:af dispatchIncomingMsg(): type: dataConfirm, msg: {"status":0,"endpoint":1,"transid":2} +4s
  zigbee-shepherd:msgHdlr IND <-- AF:dataConfirm, transId: 2 +4s
  zigbee-shepherd:af dispatchIncomingMsg(): type: incomingMsg, msg: {"groupid":0,"clusterid":1280,"srcaddr":61886,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":68,"securityuse":0,"timestamp":15647785,"transseqnumber":0,"len":6,"data":{"type":"Buffer","data":[8,2,4,112,16,0]}} +4ms
  zigbee-shepherd:msgHdlr IND <-- AF:incomingMsg, transId: 0 +7ms
  zigbee-shepherd:af dispatchIncomingMsg(): type: zclIncomingMsg, msg: {"groupid":0,"clusterid":1280,"srcaddr":61886,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":68,"securityuse":0,"timestamp":15647785,"transseqnumber":0,"len":6,"data":{"0":8,"1":2,"2":4,"3":112,"4":16,"5":0},"zclMsg":{"frameCntl":{"frameType":0,"manufSpec":0,"direction":1,"disDefaultRsp":0},"manufCode":0,"seqNum":2,"cmdId":"writeRsp","payload":[{"status":112,"attrId":16}]}} +4ms
  zigbee-shepherd:request REQ --> AF:dataRequest, transId: 3 +3s
  zigbee-shepherd-converters:devices Configured '(cb) => device.write('ssIasZone', 'iasCieAddr', coordinator.device.getIeeeAddr(), cb)' with result 'Error: request unsuccess: 112' +4s
  zigbee2mqtt:warn 7/27/2019, 11:16:21 AM Failed to configure 0x000d6f0010660529 (0x000d6f0010660529) ('Error: request unsuccess: 112') (attempt #1)
  zigbee2mqtt:warn 7/27/2019, 11:16:21 AM This can be ignored if the device is working properly

**Comment by stkang** [comment]
@johnnyletrois help

**Comment by johnnyletrois** [comment]
Yes sometimes get that error but the device works properly.  Check your configuration.yaml file to see if the device was added.

**Comment by stkang** [comment]
@johnnyletrois Ok, Thank you
