### ISSUE TITLE
Support for Xiaomi Aqara B1 curtain motor

### ISSUE THREAD

**Issue by BarBaar44** [Koenkk/zigbee-shepherd-converters#545]
trying to add a Xiaomi Aqara B1 to devices.js:

```
{
    zigbeeModel: ['lumi.curtain.hagl04'],
    model: 'ZNCLDJ12LM', 
    vendor: 'Xiaomi', 
    description: 'Aqara curtain motor ', 
    supports: 'open, close, stop, position', 
    fromZigbee: [],
    toZigbee: [],
},
```
But I'm getting the following error:

```
019-07-29T17:57:19: PM2 log: App [npm:0] online
> zigbee2mqtt@1.5.1 start /zigbee2mqtt-1.5.1
> node index.js
/zigbee2mqtt-1.5.1/node_modules/zigbee-shepherd-converters/devices.js:3
    model: 'ZNCLDJ12LM', 
         ^
SyntaxError: Unexpected token :
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/zigbee2mqtt-1.5.1/node_modules/zigbee-shepherd-converters/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
npm
```
What am I doing wrong?

**Comment by Koenkk** [comment]
Replace `devices.js` with https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js and add your section there.

**Comment by BarBaar44** [comment]
OK, and for fromZigbee.js and toZigbee.js?

Create a directory $DATA_PATH/converters and add/edit both files?

**Comment by Koenkk** [comment]
yes

**Comment by BarBaar44** [comment]
OK, think I got it figured.

The B1 (ZNCLDJ12LM) appears to be the same as the existing Xiaomi curtain (ZNCLDJ11LM). So I created the following mapping in devices.js:

[code]
    {
        zigbeeModel: ['lumi.curtain.hagl04'],
        model: 'ZNCLDJ12LM', 
        vendor: 'Xiaomi', 
        description: 'Aqara curtain motor ', 
        supports: 'open, close, stop, position', 
        fromZigbee: [
            fz.ZNCLDJ11LM_curtain_genAnalogOutput_change, fz.ZNCLDJ11LM_curtain_genAnalogOutput_report,
            fz.ignore_closuresWindowCovering_change, fz.closuresWindowCovering_report,
            fz.ignore_basic_change, fz.ignore_basic_report,
        ],
        toZigbee: [tz.ZNCLDJ11LM_control],
    },
[/code]

I do not get any errors anymore in the zigbee2mqtt log with this config. I would expect te B1 to report its battery value, but that's for later.

So this might be an easy one :)

Now, where do I find lib/extension/homeassistant.js on hassio?

**Comment by Koenkk** [comment]
@BarBaar44 enter the container with e.g. `docker exec -it zigbee2mqtt /bin/bash`, I would expect you will see the zigbee2mqtt directory when doing a `ls /`

**Comment by freenetwork** [comment]
I can control b1 motor as none battery motor. But i cant get position responce. :( i enable debugging. Position can 0,1,2. 
Im cope devices.js and add copy section non battery motor. Only change device model string

 zigbee2mqtt:info 8/19/2019, 12:36:09 AM MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c739072', payload '{"position":0,"running":true,"linkquality":52}'

**Comment by freenetwork** [comment]
I use code 

    {
        zigbeeModel: ['lumi.curtain.hagl04'],
        model: 'ZNCLDJ11LM', 
        vendor: 'Xiaomi', 
        description: 'Aqara curtain motor ', 
        supports: 'open, close, stop, position', 
        fromZigbee: [
            fz.ZNCLDJ11LM_curtain_genAnalogOutput_change, fz.ZNCLDJ11LM_curtain_genAnalogOutput_report,
            fz.ignore_closuresWindowCovering_change, fz.closuresWindowCovering_report,
            fz.ignore_basic_change, fz.ignore_basic_report,
        ],
        toZigbee: [tz.ZNCLDJ11LM_control],
    },

**Comment by BarBaar44** [comment]
> I can control b1 motor as none battery motor. But i cant get position responce. :( i enable debugging. Position can 0,1,2.
> Im cope devices.js and add copy section non battery motor. Only change device model string
> 
> ```
>  zigbee2mqtt:info 8/19/2019, 12:36:09 AM MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c739072', payload '{"position":0,"running":true,"linkquality":52}'
> zigbee2mqtt:info 8/19/2019, 12:36:09 AM MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c739072', payload '{"position":1,"running":false,"linkquality":52}'
> ```

As far as I understand, positioning currently isn't supported for the old  (ZNCLDJ11LM) model either. 

See[this pull request](https://github.com/Koenkk/zigbee-shepherd-converters/pull/498). As soon as that's implemented, it should work for the B1 as well

**Comment by freenetwork** [comment]
Ok. I capture packets.
https://github.com/freenetwork/ZNCLDJ12LM

**Comment by BarBaar44** [comment]
@freenetwork is this already working for you?

No luck here... or at least, the B1 is not auto-discovered :(

**Comment by BarBaar44** [comment]
> @BarBaar44 enter the container with e.g. `docker exec -it zigbee2mqtt /bin/bash`, I would expect you will see the zigbee2mqtt directory when doing a `ls /`

@Koenkk Found that, but changing this file is not 'restart-proof'.

How do I change homeassistant.js in such way that changes will still be there after a reboot?

**Comment by Koenkk** [comment]
@BarBaar44 what is the current state? If the device is working a PR should be made, I will then add it to homeassistant.js.

**Comment by BarBaar44** [comment]
@Koenkk sorry for my late reply. Finally found time to work in this again.

The cover is working with this config:

`    {
        zigbeeModel: ['lumi.curtain.hagl04'],
        model: 'ZNCLDJ12LM', 
        vendor: 'Xiaomi', 
        description: 'Aqara curtain motor ', 
        supports: 'open, close, stop, position', 
        fromZigbee: [
            fz.ZNCLDJ11LM_curtain_genAnalogOutput_change, fz.ZNCLDJ11LM_curtain_genAnalogOutput_report,
            fz.ignore_closuresWindowCovering_change, fz.closuresWindowCovering_report,
            fz.ignore_basic_change, fz.ignore_basic_report,
        ],
        toZigbee: [tz.ZNCLDJ11LM_control],
    },`

I am basically linking it to the existing ZNCLDJ11LM and thus giving the same control options (open/close).

So please add it (sorry, not familiar with making pull-requests) and add it to homeassistant.js

**Comment by BarBaar44** [comment]
Still a small problem. The state of the cover is not monitored properly. I have added the cover manually:

`cover:
  - platform: "mqtt"
    name: "gordijn"
    state_topic: "zigbee2mqtt/0x04cf8cdf3c738d2c"	
    availability_topic: "zigbee2mqtt/bridge/state"
    command_topic: "zigbee2mqtt/0x04cf8cdf3c738d2c/set"
    position_topic: true
    set_position_topic: true
    set_position_template: "{ \"position\": {{ position }} }"
    value_template: "{{ value_json.position }}"
`
cover.open and cover.close work. But cover.toggle does not. I have also changed the config (see above to state_topic: false. But that doesn't help either)

**Comment by Koenkk** [comment]
Can you provide the zigbee2mqtt  debug logging when executing the toggle?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by BarBaar44** [comment]
```
Current configuration.yaml:
devices: '[]'
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://*****'
  user: ******
  password: *******
serial:
  port: /dev/ttyACM0
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blacklist: []
ban: []
whitelist: []
queue: {}
```
Logoutput:
`
9/29/2019, 3:03:38 PM - info: Zigbee publish to device '0x04cf8cdf3c738d2c', genAnalogOutput - write - [{"attrId":85,"dataType":57,"attrData":0}] - {"manufSpec":0,"disDefaultRsp":0} - 1
9/29/2019, 3:04:00 PM - info: Zigbee publish to device '0x04cf8cdf3c738d2c', genAnalogOutput - write - [{"attrId":85,"dataType":57,"attrData":0}] - {"manufSpec":0,"disDefaultRsp":0} - 1
9/29/2019, 3:04:31 PM - info: Zigbee publish to device '0x04cf8cdf3c738d2c', genAnalogOutput - write - [{"attrId":85,"dataType":57,"attrData":0}] - {"manufSpec":0,"disDefaultRsp":0} - 1
`
Output from MQTT-sniffing:
`zigbee2mqtt/0x04cf8cdf3c738d2c/set CLOSE`

The output should be OPEN instead of CLOSE

**Comment by Koenkk** [comment]
I think the toggle doesn't work because the state is `unknown` in HA.

Can you provide the debug logging after opening, closing, and setting the position to 25 of the curtains via home assistant?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by BarBaar44** [comment]
Sure!
Open
`  zigbee2mqtt:info 10/4/2019, 10:10:47 AM MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c738d2c', payload '{"position":0,"running":true,"linkquality":13}'
  zigbee2mqtt:info 10/4/2019, 10:10:47 AM MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c738d2c', payload '{"position":0,"running":false,"linkquality":13}'
  zigbee2mqtt:info 10/4/2019, 10:11:50 AM Zigbee publish to device '0x04cf8cdf3c738d2c', genAnalogOutput - write - [{"attrId":85,"dataType":57,"attrData":100}] - {"manufSpec":0,"disDefaultRsp":0} - 1`
Close
`zigbee2mqtt:info 10/4/2019, 10:08:51 AM Zigbee publish to device '0x04cf8cdf3c738d2c', genAnalogOutput - write - [{"attrId":85,"dataType":57,"attrData":100}] - {"manufSpec":0,"disDefaultRsp":0} - 1
  zigbee2mqtt:info 10/4/2019, 10:09:05 AM MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c738d2c', payload '{"position":2,"running":true,"linkquality":34}'
  zigbee2mqtt:info 10/4/2019, 10:09:05 AM MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c738d2c', payload '{"position":2,"running":false,"linkquality":34}'
  zigbee2mqtt:info 10/4/2019, 10:09:05 AM MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c738d2c', payload '{"position":0,"running":true,"linkquality":34}'
  zigbee2mqtt:info 10/4/2019, 10:09:05 AM MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c738d2c', payload '{"position":0,"running":false,"linkquality":34}'
  zigbee2mqtt:info 10/4/2019, 10:10:33 AM Zigbee publish to device '0x04cf8cdf3c738d2c', genAnalogOutput - write - [{"attrId":85,"dataType":57,"attrData":0}] - {"manufSpec":0,"disDefaultRsp":0} - 1`
Set to 25
I do not get anything in the zigbee2mqtt output. However, see below for the MQTT output

And corresponding MQTT output
Open
`zigbee2mqtt/0x04cf8cdf3c738d2c/set OPEN`
Close
`zigbee2mqtt/0x04cf8cdf3c738d2c/set CLOSE`
Set to 25
`True { "position": 25 }`

**Comment by Koenkk** [comment]
@BarBaar44 can you contact me on telegram? (koenkk)

**Comment by Koenkk** [comment]
Supported in latest dev now.
