### ISSUE TITLE
Trying to add Gledopto Wall Switch GL-W-001Z, status does not change in Home Assistant!

### ISSUE THREAD

**Issue by kvvoff** [Koenkk/zigbee-shepherd-converters#547]
I'm trying to add Gledopto Wall Switch GL-W-001Z.
Product link: https://aliexpress.com/item/33013598809.html

zigbee2mqtt v 1.4.0 hasso addon

  _"zigbee_shepherd_devices": true,_

in devices.js:

`    {
        zigbeeModel: ['GL-W-001Z'],
        model: 'GL-W-001Z',
        description: 'Wall On/Off Smart switch 1 gang',
        vendor: 'Gledopto',
        supports: 'on/off',
        fromZigbee: [fz.state, fz.ignore_onoff_change],
        toZigbee: [tz.on_off],
    },`

in my database.db:

`{"id":8,"type":"Router","ieeeAddr":"0x00124b001d43e3cc","nwkAddr":1409,"manufId":0,"epList":[11,13],"status":"online","joinTime":1564484617,"endpoints":{"11":{"profId":49246,"epId":11,"devId":0,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{}},"13":{"profId":49246,"epId":13,"devId":0,"inClusterList":[4096],"outClusterList":[4096],"clusters":{}}},"_id":"7pcsvxuUqHbiqz9m"}
{"id":8,"type":"Router","ieeeAddr":"0x00124b001d43e3cc","nwkAddr":1409,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-W-001Z","epList":[11,13],"status":"online","joinTime":1564484617,"endpoints":{"11":{"profId":49246,"epId":11,"devId":0,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{}},"13":{"profId":49246,"epId":13,"devId":0,"inClusterList":[4096],"outClusterList":[4096],"clusters":{}}},"_id":"7pcsvxuUqHbiqz9m"}
{"id":8,"type":"Router","ieeeAddr":"0x00124b001d43e3cc","nwkAddr":1409,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-W-001Z","epList":[11,13],"zclVersion":1,"appVersion":1,"stackVersion":2,"hwVersion":1,"swBuildId":"1.0.0","status":"online","joinTime":1564484617,"endpoints":{"11":{"profId":49246,"epId":11,"devId":0,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{}},"13":{"profId":49246,"epId":13,"devId":0,"inClusterList":[4096],"outClusterList":[4096],"clusters":{}}},"dateCode":"20131206","_id":"7pcsvxuUqHbiqz9m"}
{"id":8,"type":"Router","ieeeAddr":"0x00124b001d43e3cc","nwkAddr":1409,"manufId":0,"manufName":"GLEDOPTO","powerSource":"Mains (single phase)","modelId":"GL-W-001Z","epList":[11,13],"zclVersion":1,"appVersion":1,"stackVersion":2,"hwVersion":1,"swBuildId":"1.0.0","status":"online","joinTime":1564484617,"endpoints":{"11":{"profId":49246,"epId":11,"devId":0,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{"genBasic":{"dir":{"value":1},"attrs":{}},"genIdentify":{"dir":{"value":1},"attrs":{}},"genGroups":{"dir":{"value":1},"attrs":{}},"genScenes":{"dir":{"value":1},"attrs":{}},"genOnOff":{"dir":{"value":1},"attrs":{}}}},"13":{"profId":49246,"epId":13,"devId":0,"inClusterList":[4096],"outClusterList":[4096],"clusters":{"lightLink":{"dir":{"value":3},"attrs":{}}}}},"dateCode":"20131206","_id":"7pcsvxuUqHbiqz9m"}
`
in Home Assistant light.yaml:

`  - platform: "mqtt"
    state_topic: "zigbee2mqtt/0x00124b001d43e3cc"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/0x00124b001d43e3cc/set"
`

The problem is that **from the Home Assistant I can control the switch**, but when I physically press the switch sensor, the **status does not change** in Home Assistant! 

**I ask for help in setting up**

**Comment by BudBundi** [comment]
Have you tried to activate the report function?

**Comment by kvvoff** [comment]
@BudBundi did not try.  how to do it?

**Comment by BudBundi** [comment]
https://www.zigbee2mqtt.io/configuration/configuration.html

Advanced:
  Report:true

**Comment by kvvoff** [comment]
@BudBundi I added **report:true**
I also added **log_level:debug**


But when I turn it on and off, I do not see any messages in the log. Here is what I see:

![Screenshot_20190731-124811](https://user-images.githubusercontent.com/38342171/62204130-3d36a080-b395-11e9-8d43-88360ded213a.png)

I used zigbee2mqtt **v1.4.0** hasso addon

**Comment by Koenkk** [comment]
Devices is now supported in latest zigbee2mqtt with state changes.
