### ISSUE TITLE
Hou to add transition length when the color changes?

### ISSUE THREAD

**Issue by kvvoff** [Koenkk/zigbee-shepherd-converters#551]
I use light bulbs E27, E14 and a led controller GL-C-008 from Gledopto.
When I turn on the light - the transition length is present and the light turns on smoothly. 
When I turn off the light - it also turns off smoothly. 
**But when I change colors or change the temperature with the lights on**, everything happens at lightning speed and is unpleasant for the eyes. 
How to fix it? 
How to make the **transition** length work **not only when turned on and off**, but also **when the color changes**?

**Comment by mosanwen** [comment]
maybe because you set the “transitionTime” too big，set it small to have a try。

**Comment by kvvoff** [comment]
@mosanwen I used autodiscover mqtt in Home Assistant. How do I set “transitionTime” manually?

**Comment by kvvoff** [comment]
Here is what Gledopto answered me on email:

![image](https://user-images.githubusercontent.com/38342171/62350327-113d2b80-b50b-11e9-9654-8c357a29fb9e.png)

**Comment by mosanwen** [comment]
Yes， if you set the time to 0，the light will transition Immediately，so you can see it not so smoothly。

**Comment by kvvoff** [comment]
@mosanwen And where exactly can I set it?

**Comment by mosanwen** [comment]
can you show me the screen you set the color CMD?

**Comment by kvvoff** [comment]
@mosanwen in Home Assistant? I am not special in this, I do not quite understand

**Comment by mosanwen** [comment]
so how you set the color,what is you hub?

**Comment by kvvoff** [comment]
Sorry for that, i dont write this. I am using version zigbee2mqtt 1.5.1.1 Hassio addon on HassOS

I can manually set mqtt configuration, as in the official documentation. (https://www.zigbee2mqtt.io/devices/GL-C-008.html)
`light:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    brightness: true
    color_temp: true
    xy: true
    schema: "json"
    command_topic: "zigbee2mqtt/<FRIENDLY_NAME>/set"`

With this configuration, the light turns on as I described above. How do I set transitionTime?

**Comment by kvvoff** [comment]
Does anyone know how to make a transition time?  Maybe something to change in devices.js?

**Comment by Koenkk** [comment]
I've implemented this new feature in zigbee2mqtt.

- You need the dev branch for this
- Documentation (is available for every light but I picked a random one here): https://github.com/Koenkk/zigbee2mqtt.io/blob/develop/docs/devices/LED1536G5.md#device-type-specific-configuration
- Example: 
```yaml
  '0x000b57fffec6a5b2':
    friendly_name: 'my_bulb'
    retain: false
    transition: 2
```

**Comment by kvvoff** [comment]
@Koenkk Thank!  That's cool!  I'll try tomorrow

**Comment by kvvoff** [comment]
@Koenkk Thanks for this!  It works wonderfully!  I installed transition 0.3 and this works fine for me.  But when I choose warm white or cold white instead of color, it still turns on lightning fast.  And vice versa.  The transition does not work when I set to white and vice versa when I set to color.  I recorded a video for clarity

https://youtu.be/EspxsMq6Ej8

**Comment by Koenkk** [comment]
Does the controller support this? Can you provide the debug log when executing this command?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by kvvoff** [comment]
Restart zigbee2mqtt and set warm white color from blue color, all log:
`Log
./run.sh: line 16: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
2019-08-06T22:20:03: PM2 log: Launching in no daemon mode
2019-08-06T22:20:03: PM2 log: App [npm:0] starting in -fork mode-
2019-08-06T22:20:03: PM2 log: App [npm:0] online
> zigbee2mqtt@1.5.1 start /app
> node index.js
  zigbee2mqtt:info 8/6/2019, 10:20:10 PM Logging to directory: '/share/zigbee2mqtt/log/2019-08-06.22-20-08'
  zigbee2mqtt:debug 8/6/2019, 10:20:10 PM Removing old log directory '/share/zigbee2mqtt/log/2019-08-06.20-46-30'
  zigbee2mqtt:debug 8/6/2019, 10:20:10 PM Loaded state from file /share/zigbee2mqtt/state.json
  zigbee2mqtt:debug 8/6/2019, 10:20:10 PM Saving state to file /share/zigbee2mqtt/state.json
  zigbee2mqtt:info 8/6/2019, 10:20:11 PM Starting zigbee2mqtt version 1.5.1 (commit #unknown)
  zigbee2mqtt:info 8/6/2019, 10:20:11 PM Starting zigbee-shepherd
  zigbee2mqtt:debug 8/6/2019, 10:20:11 PM Using zigbee-shepherd with settings: '{"net":{"panId":6754,"extPanId":[221,221,221,221,221,221,221,221],"channelList":[11],"precfgkey":"HIDDEN"},"dbPath":"/share/zigbee2mqtt/database.db","coordBackupPath":"/share/zigbee2mqtt/coordinator_backup.json","sp":{"baudRate":115200,"rtscts":true}}'
  zigbee2mqtt:info 8/6/2019, 10:20:12 PM zigbee-shepherd started
  zigbee2mqtt:info 8/6/2019, 10:20:12 PM Coordinator firmware version: '20190425'
  zigbee2mqtt:debug 8/6/2019, 10:20:12 PM zigbee-shepherd info: {"enabled":true,"net":{"state":"Coordinator","channel":"11","panId":6754,"extPanId":[221,221,221,221,221,221,221,221],"ieeeAddr":"0x00124b0012013c03","nwkAddr":0},"firmware":{"transportrev":2,"product":0,"version":"2.6.3","revision":20190425},"startTime":1565119212,"joinTimeLeft":0}
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM Currently 8 devices are joined:
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM 0x00158d0001825914 (0x00158d0001825914): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM 0x00158d00025c9c05 (0x00158d00025c9c05): HGZB-06A - Nue / 3A Smart 7W E27 light bulb (Router)
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM 0x00158d00018745b5 (0x00158d00018745b5): RTCGQ01LM - Xiaomi MiJia human body movement sensor (EndDevice)
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM unknown (0x00124b001bd8472a): GL-B-008Z - Gledopto Smart 12W E27 RGB / CW LED bulb (Router)
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM unknown (0x00124b001bd844d9): GL-B-007Z - Gledopto Smart 6W E27 RGB / CW LED bulb (Router)
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM 0x00124b001b6b4346 (0x00124b001b6b4346): GL-B-001Z - Gledopto Smart 4W E14 RGB / CW LED bulb (Router)
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM 0x00124b001d43e3cc (0x00124b001d43e3cc): unkown - undefined unknown (Router)
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM 0x00124b001a13f7aa (0x00124b001a13f7aa): GL-C-008 - Gledopto Zigbee LED controller RGB + CCT / RGBW / WWCW / Dimmer (Router)
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM Zigbee: disabling joining new devices.
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM Connecting to MQTT server at mqtt://homeassistant
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM zigbee-shepherd ready
  zigbee2mqtt:debug 8/6/2019, 10:20:13 PM Mounted the cieApp (epId 11)
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM Connected to MQTT server
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'zigbee2mqtt/0x00158d0001825914', payload '{"temperature":27.7,"linkquality":49,"humidity":42.91,"battery":100,"voltage":3015}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'zigbee2mqtt/bedroom_bulbs', payload '{"color":{"x":0.427,"y":0.404,"saturation":51.2},"state":"ON","brightness":247,"color_temp":480}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'zigbee2mqtt/0x00158d00025c9c05', payload '{"state":"ON","color":{"x":0.427,"y":0.404,"saturation":51.2},"brightness":252,"color_temp":312,"linkquality":42}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'zigbee2mqtt/0x00158d00018745b5', payload '{"occupancy":false,"linkquality":76,"battery":100,"voltage":3035}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'zigbee2mqtt/0x00124b001bd8472a', payload '{"state":"OFF","brightness":13,"color":{"x":0.477,"y":0.196},"color_temp":335}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'zigbee2mqtt/0x00124b001bd844d9', payload '{"state":"OFF","brightness":167,"color_temp":312,"color":{"x":0.38,"y":0.17}}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'zigbee2mqtt/bedroom_bulbs', payload '{"color":{"x":0.167,"y":0.341,"saturation":51.2},"state":"ON","brightness":247,"color_temp":480}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'zigbee2mqtt/0x00124b001b6b4346', payload '{"state":"ON","color_temp":153,"brightness":255,"color":{"x":0.167,"y":0.341}}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'zigbee2mqtt/0x00124b001d43e3cc', payload '{"state":"ON"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'zigbee2mqtt/bedroom_bulbs', payload '{"color":{"x":0.326,"y":0.175,"saturation":51.2},"state":"ON","brightness":247,"color_temp":480}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'zigbee2mqtt/0x00124b001a13f7aa', payload '{"state":"ON","brightness":247,"color_temp":480,"color":{"x":0.326,"y":0.175}}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'homeassistant/sensor/0x00158d0001825914/temperature/config', payload '{"unit_of_measurement":"°C","device_class":"temperature","value_template":"{{ value_json.temperature }}","state_topic":"zigbee2mqtt/0x00158d0001825914","json_attributes_topic":"zigbee2mqtt/0x00158d0001825914","name":"0x00158d0001825914_temperature","unique_id":"0x00158d0001825914_temperature_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d0001825914"],"name":"0x00158d0001825914","sw_version":"Zigbee2mqtt 1.5.1","model":"MiJia temperature & humidity sensor (WSDCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'homeassistant/sensor/0x00158d0001825914/humidity/config', payload '{"unit_of_measurement":"%","device_class":"humidity","value_template":"{{ value_json.humidity }}","state_topic":"zigbee2mqtt/0x00158d0001825914","json_attributes_topic":"zigbee2mqtt/0x00158d0001825914","name":"0x00158d0001825914_humidity","unique_id":"0x00158d0001825914_humidity_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d0001825914"],"name":"0x00158d0001825914","sw_version":"Zigbee2mqtt 1.5.1","model":"MiJia temperature & humidity sensor (WSDCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'homeassistant/sensor/0x00158d0001825914/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/0x00158d0001825914","json_attributes_topic":"zigbee2mqtt/0x00158d0001825914","name":"0x00158d0001825914_battery","unique_id":"0x00158d0001825914_battery_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d0001825914"],"name":"0x00158d0001825914","sw_version":"Zigbee2mqtt 1.5.1","model":"MiJia temperature & humidity sensor (WSDCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'homeassistant/sensor/0x00158d0001825914/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x00158d0001825914","json_attributes_topic":"zigbee2mqtt/0x00158d0001825914","name":"0x00158d0001825914_linkquality","unique_id":"0x00158d0001825914_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d0001825914"],"name":"0x00158d0001825914","sw_version":"Zigbee2mqtt 1.5.1","model":"MiJia temperature & humidity sensor (WSDCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'homeassistant/light/0x00158d00025c9c05/light/config', payload '{"brightness":true,"color_temp":true,"xy":true,"schema":"json","command_topic":"zigbee2mqtt/0x00158d00025c9c05/set","state_topic":"zigbee2mqtt/0x00158d00025c9c05","name":"0x00158d00025c9c05_light","unique_id":"0x00158d00025c9c05_light_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d00025c9c05"],"name":"0x00158d00025c9c05","sw_version":"Zigbee2mqtt 1.5.1","model":"Smart 7W E27 light bulb (HGZB-06A)","manufacturer":"Nue / 3A"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'homeassistant/sensor/0x00158d00025c9c05/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x00158d00025c9c05","json_attributes_topic":"zigbee2mqtt/0x00158d00025c9c05","name":"0x00158d00025c9c05_linkquality","unique_id":"0x00158d00025c9c05_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d00025c9c05"],"name":"0x00158d00025c9c05","sw_version":"Zigbee2mqtt 1.5.1","model":"Smart 7W E27 light bulb (HGZB-06A)","manufacturer":"Nue / 3A"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'homeassistant/binary_sensor/0x00158d00018745b5/occupancy/config', payload '{"payload_on":true,"payload_off":false,"value_template":"{{ value_json.occupancy }}","device_class":"motion","state_topic":"zigbee2mqtt/0x00158d00018745b5","json_attributes_topic":"zigbee2mqtt/0x00158d00018745b5","name":"0x00158d00018745b5_occupancy","unique_id":"0x00158d00018745b5_occupancy_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d00018745b5"],"name":"0x00158d00018745b5","sw_version":"Zigbee2mqtt 1.5.1","model":"MiJia human body movement sensor (RTCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'homeassistant/sensor/0x00158d00018745b5/battery/config', payload '{"unit_of_measurement":"%","device_class":"battery","value_template":"{{ value_json.battery }}","state_topic":"zigbee2mqtt/0x00158d00018745b5","json_attributes_topic":"zigbee2mqtt/0x00158d00018745b5","name":"0x00158d00018745b5_battery","unique_id":"0x00158d00018745b5_battery_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d00018745b5"],"name":"0x00158d00018745b5","sw_version":"Zigbee2mqtt 1.5.1","model":"MiJia human body movement sensor (RTCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'homeassistant/sensor/0x00158d00018745b5/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x00158d00018745b5","json_attributes_topic":"zigbee2mqtt/0x00158d00018745b5","name":"0x00158d00018745b5_linkquality","unique_id":"0x00158d00018745b5_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00158d00018745b5"],"name":"0x00158d00018745b5","sw_version":"Zigbee2mqtt 1.5.1","model":"MiJia human body movement sensor (RTCGQ01LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'homeassistant/light/0x00124b001b6b4346/light/config', payload '{"brightness":true,"color_temp":true,"xy":true,"schema":"json","command_topic":"zigbee2mqtt/0x00124b001b6b4346/set","state_topic":"zigbee2mqtt/0x00124b001b6b4346","name":"0x00124b001b6b4346_light","unique_id":"0x00124b001b6b4346_light_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00124b001b6b4346"],"name":"0x00124b001b6b4346","sw_version":"Zigbee2mqtt 1.5.1","model":"Smart 4W E14 RGB / CW LED bulb (GL-B-001Z)","manufacturer":"Gledopto"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'homeassistant/sensor/0x00124b001b6b4346/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x00124b001b6b4346","json_attributes_topic":"zigbee2mqtt/0x00124b001b6b4346","name":"0x00124b001b6b4346_linkquality","unique_id":"0x00124b001b6b4346_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00124b001b6b4346"],"name":"0x00124b001b6b4346","sw_version":"Zigbee2mqtt 1.5.1","model":"Smart 4W E14 RGB / CW LED bulb (GL-B-001Z)","manufacturer":"Gledopto"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'homeassistant/light/0x00124b001a13f7aa/light/config', payload '{"brightness":true,"color_temp":true,"xy":true,"schema":"json","command_topic":"zigbee2mqtt/0x00124b001a13f7aa/set","state_topic":"zigbee2mqtt/0x00124b001a13f7aa","name":"0x00124b001a13f7aa_light","unique_id":"0x00124b001a13f7aa_light_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00124b001a13f7aa"],"name":"0x00124b001a13f7aa","sw_version":"Zigbee2mqtt 1.5.1","model":"Zigbee LED controller RGB + CCT / RGBW / WWCW / Dimmer (GL-C-008)","manufacturer":"Gledopto"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'homeassistant/sensor/0x00124b001a13f7aa/linkquality/config', payload '{"unit_of_measurement":"-","value_template":"{{ value_json.linkquality }}","state_topic":"zigbee2mqtt/0x00124b001a13f7aa","json_attributes_topic":"zigbee2mqtt/0x00124b001a13f7aa","name":"0x00124b001a13f7aa_linkquality","unique_id":"0x00124b001a13f7aa_linkquality_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x00124b001a13f7aa"],"name":"0x00124b001a13f7aa","sw_version":"Zigbee2mqtt 1.5.1","model":"Zigbee LED controller RGB + CCT / RGBW / WWCW / Dimmer (GL-C-008)","manufacturer":"Gledopto"},"availability_topic":"zigbee2mqtt/bridge/state"}'
  zigbee2mqtt:info 8/6/2019, 10:20:13 PM MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.5.1","commit":"unknown","coordinator":20190425,"log_level":"debug","permit_join":false}'
  zigbee2mqtt:debug 8/6/2019, 10:21:10 PM Received MQTT message on 'zigbee2mqtt/0x00124b001a13f7aa/set' with data '{"state": "ON", "color_temp": 459}'
  zigbee2mqtt:debug 8/6/2019, 10:21:10 PM Skipping state because of Home Assistant
  zigbee2mqtt:debug 8/6/2019, 10:21:10 PM Received MQTT message on 'zigbee2mqtt/0x00124b001a13f7aa/set' with data '{"state": "ON", "color_temp": 460}'
  zigbee2mqtt:debug 8/6/2019, 10:21:10 PM Skipping state because of Home Assistant
  zigbee2mqtt:info 8/6/2019, 10:21:10 PM Zigbee publish to device '0x00124b001a13f7aa', lightingColorCtrl - moveToColorTemp - {"colortemp":459,"transtime":3} - {"manufSpec":0,"disDefaultRsp":0} - 11
  zigbee2mqtt:info 8/6/2019, 10:21:10 PM MQTT publish: topic 'zigbee2mqtt/bedroom_bulbs', payload '{"color":{"x":0.326,"y":0.175,"saturation":51.2},"state":"ON","brightness":247,"color_temp":459}'
  zigbee2mqtt:info 8/6/2019, 10:21:10 PM MQTT publish: topic 'zigbee2mqtt/0x00124b001a13f7aa', payload '{"state":"ON","brightness":247,"color_temp":459,"color":{"x":0.326,"y":0.175}}'
  zigbee2mqtt:info 8/6/2019, 10:21:10 PM Zigbee publish to device '0x00124b001a13f7aa', lightingColorCtrl - moveToColorTemp - {"colortemp":460,"transtime":3} - {"manufSpec":0,"disDefaultRsp":0} - 11
  zigbee2mqtt:info 8/6/2019, 10:21:11 PM MQTT publish: topic 'zigbee2mqtt/bedroom_bulbs', payload '{"color":{"x":0.326,"y":0.175,"saturation":51.2},"state":"ON","brightness":247,"color_temp":460}'
  zigbee2mqtt:info 8/6/2019, 10:21:11 PM MQTT publish: topic 'zigbee2mqtt/0x00124b001a13f7aa', payload '{"state":"ON","brightness":247,"color_temp":460,"color":{"x":0.326,"y":0.175}}'`

**Comment by kvvoff** [comment]
@Koenkk Did this log give you any information? Maybe me need to do something else?

**Comment by Koenkk** [comment]
I see the `transtime` being published with the correct value, can you check if the controller supports it by publishing a manual message to `zigbee2mqtt/0x00124b001a13f7aa/set` `{"state": "ON", "color_temp": 459, "transition": 3}`? Does it give you a transition of +- 3 seconds?

**Comment by kvvoff** [comment]
@Koenkk  This works in exactly the same way as from the home Assistant user interface.  
Video: https://youtu.be/fAUreMrB2ys
As you can see in the video, when it’s cold white and I run this command (it doesn’t matter manually through the publication or from the interface) and I turn on warm white, it works smoothly.  The transition from white to color (purple in the video) is also beautiful and smooth.  but From color to white it turns on lightning fast.  This applies equally to all of my Gledopto devices.  I can’t check now, but next week I will check the light bulb from Zemismart.  p.s, I also replaced 3 with 0.3 otherwise it was a very very long time on the video)

**Comment by kvvoff** [comment]
@Koenkk Hi, I tested another light bulb from Zemismart, it always switches smoothly.  Apparently Gledopto devices do not support this.  Thanks for the transition time, this is a useful feature

**Comment by Koenkk** [comment]
@kvvoff thanks for the update!
