### ISSUE TITLE
Cannot convert zy back to rgb due to losst of percision

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-shepherd-converters#564]
When passing rgb values to an IKEA bulb, they are converted by utils.js to zy using:
https://github.com/usolved/cie-rgb-converter/blob/master/cie_rgb_converter.js

However using the reverse function on the reported xy value does not result in the same rgb values, I found this out when trying to link a bulb to homekit using node-red.

I did find a solution for it, changing the precision from 3 to 4 fixes it, so the zigbee bulb is passing the correct values but we are rounding them here:
- https://github.com/Koenkk/zigbee-shepherd-converters/blob/af8fddd76a70d7123028b193931367d83c6edeb0/converters/fromZigbee.js#L711
- https://github.com/Koenkk/zigbee-shepherd-converters/blob/af8fddd76a70d7123028b193931367d83c6edeb0/converters/fromZigbee.js#L715
- https://github.com/Koenkk/zigbee-shepherd-converters/blob/af8fddd76a70d7123028b193931367d83c6edeb0/converters/fromZigbee.js#L753
- https://github.com/Koenkk/zigbee-shepherd-converters/blob/af8fddd76a70d7123028b193931367d83c6edeb0/converters/fromZigbee.js#L757

I will open a PR for this, after the fix the following works:
1. send a `{"color": {"r":205,"g":221,"b":255}}` (cool white) to a tradfri bulb
2. pass the result of the report to the reverse function from cgi_rb_converter `{"color":{"x":0.2805,"y":0.2908}}`
3. we now have a matching `{"r":205,"g":221,"b":255}` result

**Comment by Koenkk** [comment]
Fixed as https://github.com/Koenkk/zigbee-shepherd-converters/pull/565 got merged.
