### ISSUE TITLE
Osram Smart+ Classic E27 Multicolor different models issue

### ISSUE THREAD

**Issue by Vuistzwaan** [Koenkk/zigbee-shepherd-converters#575]
I bought 4 "**Osram Smart+ Classic E27 Multicolor**", which seem to have different models.

2 of them are [**AC03645**](https://www.zigbee2mqtt.io/devices/AC03645.html), which work great with zigbee2mqtt in combination with hass.

The other 2 are [**AC03647**](https://www.zigbee2mqtt.io/devices/AC03647.html), which do work, but they don't work as great as the AC03645 ones. The color range on low brightness is more limited.

(The image on the supported devices page also show's a different bulb. Could it be that the same model number is used for different bulbs?)

Is it possible to improve the color range on low brightness in the shepherd converters? (Just like the AC03645 model) Or could it be that the AC03647 bulbs have an outdated firmware version? (I don't have a lightify gateway, so I don't know the firmware version of the bulbs)

Osram RGB 1 (0x7cb03eaa00ae35ee): AC03645 - OSRAM LIGHTIFY LED CLA60 E27 RGBW (Router)
Osram RGB 2 (0x7cb03eaa00ae3a3f): AC03645 - OSRAM LIGHTIFY LED CLA60 E27 RGBW (Router)
Osram RGB 3 (0xf0d1b8000010c3c1): AC03647 - OSRAM SMART+ LED CLASSIC E27 RGBW (Router)
Osram RGB 4 (0xf0d1b8000010adc6): AC03647 - OSRAM SMART+ LED CLASSIC E27 RGBW (Router)

I'm using the latest zigbee2mqtt-edge version.

I've also added 2 pictures of the bulbs and the boxes they come in. Might be helpfull for people who have the same issue. (The boxes of the models look slightly different.)
![IMG_20190820_160038](https://user-images.githubusercontent.com/21459252/63354119-24058c00-c364-11e9-8aae-5647509e1303.jpg)
![IMG_20190820_160028](https://user-images.githubusercontent.com/21459252/63354121-24058c00-c364-11e9-95ce-b089f0f3e710.jpg)

**Comment by Koenkk** [comment]
We can not improve things from the zigbee2mqtt side. The commands used are generic commands (which are the same for almost every bulb from every manufacturer). 

Probably the hardware or software of these bulbs is just different.

**Comment by Vuistzwaan** [comment]
Thanks for your reply, I'll try to get my hands on a gateway/hub so I can update the software and see if this will improve the color range.

**Comment by jasperro** [comment]
> Thanks for your reply, I'll try to get my hands on a gateway/hub so I can update the software and see if this will improve the color range.

I'm having the same problem, I also have a AC03647. When setting the color to red with a high brightness it becomes pink and my orange looks grey. If you got the gateway, did a software update fix the issue?

**Comment by Vuistzwaan** [comment]
> I'm having the same problem, I also have a AC03647. When setting the color to red with a high brightness it becomes pink and my orange looks grey. If you got the gateway, did a software update fix the issue?

Haven't found a gateway, they seem quite hard to get in the Netherlands for a good price.

**Comment by jasperro** [comment]
I just found out that the bulbs produce the same colors when you use hue and saturation.
Try `mosquitto_pub -h 192.168.1.16 -u mosquitto -P mosquittomqtt -t "zigbee2mqtt/light/set" -m "{\"co    lor\":{\"hue\": 0,\"saturation\": 300},\"color_mode\":2,\"brightness\":255}"`
with your lights.

**Comment by jasperro** [comment]
@Koenkk I got hue/saturation in home assistant working in my fork, but the only issue is that home assistant sends the hue and saturation as `"color":{"h":100,"s":100}` and the zigbee device expects `"color":{"hue":100,"saturation":100}` Is this something that needs to be fixed in home assistant or zigbee2mqtt?

**Comment by Koenkk** [comment]
@jasperro in zigbee2mqtt, also add `h` and `s` here: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/toZigbee.js#L371

**Comment by jasperro** [comment]
@Koenkk this works, but the color state is not updated in home assistant. Does the x/y still need to be sent to home assistant for the color wheel and the icon of the light?

**Comment by jasperro** [comment]
@Koenkk I've tried to implement the sending of x and y to state in my pull request, but I haven't had much luck. Could you please look at the code to see why it isn't working?

**Comment by jasperro** [comment]
@Koenkk everything now works perfectly, in home assistant too. I've made pull requests in all repos with changes, pulls here, I also added motion detection button support for AC01353010G and iL07_1 to home assistant:
https://github.com/Koenkk/zigbee-herdsman-converters/pull/841
https://github.com/Koenkk/zigbee2mqtt/pull/2603
https://github.com/Koenkk/zigbee2mqtt.io/pull/179
