### ISSUE TITLE
Support for new INNR RF 265

### ISSUE THREAD

**Issue by ArJay60** [Koenkk/zigbee-shepherd-converters#585]
Can one add support for INNR RF 265? Lamp is equal to INNR RB 265 but then with transparant bulb and led filament. https://shop.innrlighting.com/nl/shop/203/smart-filament-bulb-white-e27

**Comment by Koenkk** [comment]
If you are able to provide me the model ID I can do it: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Also does it support color temperature or only brightness?

**Comment by ArJay60** [comment]
It does only support brightness.

Output of log:

,{"ieeeAddr":"                                                                                                             0xcccccccccccccccc","type":"Router","model":"RF 265","friendly_name":"Tuinkamerb                                                                                                             ar rechts"}]}'

It should be the same as the RB 265 from INNR. Only difference is that this type is transparant bulb and ledfilament. 

Thanks for your support.

**Comment by Koenkk** [comment]
I've just checked, but it seems support has already been added: https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/devices.js#L1664
