### ISSUE TITLE
Hive 1613V not supported, but supported

### ISSUE THREAD

**Issue by DubhAd** [Koenkk/zigbee-shepherd-converters#596]
I've just installed [one of these](https://www.zigbee2mqtt.io/devices/1613V.html)

When I connected it, I got:

```
zigbee2mqtt:info 9/5/2019, 5:05:26 PM New device 'SLP2b' with address 0x001e5e090232920d connected!
```

Z2M then crashed and restarted as normal, and I get:

```
zigbee2mqtt:info 9/5/2019, 5:05:30 PM 0x001e5e090232920d (0x001e5e090232920d): unkown - undefined unknown (Router)
```

Yet checking the converters shows the config. I'm confused.

Zigbee2MQTT 1.5.1.

**Comment by Koenkk** [comment]
Can you provide your `database.db` and full startup log?

**Comment by DubhAd** [comment]
database.db [is here](https://paste.ubuntu.com/p/P7q8jyzkRK/)

startup log is [here](https://paste.ubuntu.com/p/YtQCGpgtGd/)

**Comment by DubhAd** [comment]
And... after another few restarts, it mysteriously works 🤷‍♂

**Comment by Koenkk** [comment]
Ok, great, this might be due to zigbee-shepherd and be solved by zigbee-herdsman.
