### ISSUE TITLE
New model for IKEA LED1624G9

### ISSUE THREAD

**Issue by erwinvana** [Koenkk/zigbee-shepherd-converters#599]
My new IKEA LED1624G2 is identified as _'TRADFRI bulb E14 CWS opal 600lm'_
and was reported is a not supported device

devices.js i found that the LED1624G9 was already present for the E27/E26 type.

Once i changed the zigbeemodel for the IKEA LED1624G9 to include the _'TRADFRI bulb E14 CWS opal 600lm'_ is was correctly detected.
My device is an E14 model so i updated teh Discription as well.
The entree in "ode_modules/zigbee-shepherd-converters/devices.js" for the IKEA LED1625G9 looks like this for me now :
`{
        zigbeeModel: ['TRADFRI bulb E27 CWS opal 600lm', 'TRADFRI bulb E26 CWS opal 600lm', 'TRADFRI bulb E14 CWS opal 600lm'],
        model: 'LED1624G9',
        vendor: 'IKEA',
        description: 'TRADFRI LED bulb E14/E27/E26 600 lumen, dimmable, color, opal white',
        extend: generic.light_onoff_brightness_colorxy,
    },`

I'm new to Github and i'm not sure if this is the correct way to report this, but i hope it is helpfull.

Kr. Erwin

**Comment by Koenkk** [comment]
This device has already been added support for (https://github.com/Koenkk/zigbee-shepherd-converters/pull/529). It will be included in the next zigbee2mqtt release (1.6).
