### ISSUE TITLE
attr: [] in toZigbee.js unused/ irrelevant?

### ISSUE THREAD

**Issue by sebastianheierhoff** [Koenkk/zigbee-shepherd-converters#61]
Hi all,

might be a dumb question, but what do we have the attr: [] in toZigbee.js for? Is this ever used or could we just discard it?

Regards,
Sebastian

**Comment by Koenkk** [comment]
It defines the attribute that converter affect (which are none for the factory reset). Zigbee2mqtt uses it to poll for changes.

**Comment by sebastianheierhoff** [comment]
Thanks for the clarification! Will close the issue.
