### ISSUE TITLE
Code to support Nue3A Plug HGZB-20A

### ISSUE THREAD

**Issue by rm2kdev** [Koenkk/zigbee-shepherd-converters#616]
I'm not 100% sure how to get this into your code, but here you go i just whipped this up this weekend, it works with the Australian version HGZB-20A (Nue/3A Power Plug) 1 button, australian/chinese socket.

    {
        zigbeeModel: ['FNB56-SKT1JXN1.0'],
        model: 'HGZB-20A',
        vendor: 'Nue / 3A',
        description: 'Power plug',
        supports: 'on/off',
        fromZigbee: [fz.state_change],
        toZigbee: [tz.on_off],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 11);
            execute(device, [(cb) => device.bind('genOnOff', coordinator, cb)], callback);
        },
    },

**Comment by Koenkk** [comment]
Can you provide an URL to the device?

**Comment by rm2kdev** [comment]
This is what i purchased however what they sent was a little different (i think maybe they sent a newer model) i cant find a product page from them for the exact device they sent so ill attach some photos of what I received.

https://www.amazon.com.au/Nue-ZigBee-Outlet-Compatible-Automation/dp/B07L6Y9H8K/ref=sr_1_1?keywords=nue+smart+plug&qid=1568762474&s=gateway&sr=8-1

ignore the SM2A Label i put that on there to help identify them when setting up node-red

![IMG_20190918_072351](https://user-images.githubusercontent.com/845245/65086752-8db99a00-d9e5-11e9-8102-0104e0513dd5.jpg)
![IMG_20190918_072402](https://user-images.githubusercontent.com/845245/65086754-901bf400-d9e5-11e9-8da6-a6057144d9e9.jpg)
![IMG_20190918_072407](https://user-images.githubusercontent.com/845245/65086756-90b48a80-d9e5-11e9-81b6-b89d331b74a5.jpg)

**Comment by rm2kdev** [comment]
Just to add some notes the device handler i put up the top works perfect with these.
They report power state when the button is pressed, and support control on and off when using /devid/set {"state":"ON/OFF"}

**Comment by Koenkk** [comment]
Added, thanks!
