### ISSUE TITLE
Sercomm SZ-ESW01

### ISSUE THREAD

**Issue by coolguymatt** [Koenkk/zigbee-shepherd-converters#619]
Trying to add support for Sercomm SZ-ESW01 (different than SZ-ESW01-AU apparently). I was copying the work done in https://github.com/Koenkk/zigbee2mqtt/issues/1500 but it says to edit fromZigbee.js. Is that possible using the hassio addon?

```
    // Sercomm SZ-ESW01
    {
        zigbeeModel: ['SZ-ESW01'],
        model: 'SZ-ESW01',
        vendor: 'Sercomm',
        description: 'Telstra smart plug',
        supports: 'on/off, power consumption',
        fromZigbee: [fz.state, fz.state_change, fz.SZ_ESW01_AU_power, fz.ignore_metering_change],
        toZigbee: [tz.on_off],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 1);
            const cfg = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 1000, repChange: 0};
            const actions = [
                (cb) => device.bind('genOnOff', coordinator, cb),
                (cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg, cb),
                (cb) => device.report('seMetering', 'instantaneousDemand', 10, 60, 1, cb),
            ];

            execute(device, actions, callback);
        },
    },
```

**Comment by Koenkk** [comment]
Does this device work when adding the `zigbeeModel` of your device to the one of SZ-ESW01-AU? In that case modifying `fromZigbee.js` isn't needed.

**Comment by coolguymatt** [comment]
I was having issues with zigbee2mqtt crashing when I tried to add the SZ-ESW01 as a separate device type. Instead I went into the database file and just changed the device from SZ-ESW01 to SZ-ESW01-AU and it works fine.

**Comment by Koenkk** [comment]
OK, added, will be supported in the next zigbee2mqtt version. Thanks!

**Comment by coolguymatt** [comment]
Sorry if this is a dumb question, but if I use the edge version of zigbee2mqtt in hassio, will this device work or I would need to wait?

**Comment by Koenkk** [comment]
This device is supported in the edge version now.
