### ISSUE TITLE
TRADFRI bulb E27 WW 806lm not supported (yet)

### ISSUE THREAD

**Issue by schumi2004** [Koenkk/zigbee-shepherd-converters#624]
Bought myself a TRADFRI bulb E27 WW 806lm to find out it's not (yet) supported.
I checked what is needed and if i'm correct this should be sufficient to be added to devices.js

    {
        zigbeeModel: ['TRADFRI bulb E27 WW 806lm'],
        model: 'LED1836G9',
        vendor: 'IKEA',
        description: 'TRADFRI bulb E27 WW 806lm, dimmable',
        extend: generic.light_onoff_brightness,
    },

There is only 1 issue, i can't test it. I'm running zigbee2mqtt in Hass.io and i have no idea (yet) how to properly rebuild the addon and include this new device.

I can make a pull request but like i said can't test it so it doesn't make sense to submit a PR.

Any ideas?

**Comment by Kryzek** [comment]
For HA discovery you need to add device also into https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/homeassistant.js

**Comment by schumi2004** [comment]
Okay I should add below line there somewere around line 456 but is it really needed?

    'LED1836G9': [configurations.light_brightness],

But that's not for this repo but will have a look at it when i found an option to compile/test.
Any suggestions for how to compile/build this new device?

**Comment by barrygwn** [comment]
I also bought myself this bulb, and I am running zigbee2mqtt stand-alone so I was able to test and add the bulb to the devices.js. I have created a pull request that passes all tests so I'll expect it to be merged soon.

**Comment by Koenkk** [comment]
Merged the pr from @barrygwn, thanks all!

Will be supported in the dev branch in a few hours.
