### ISSUE TITLE
FR: Can the AQARA Smart hub cube (MFKZQ01LM) use a single attribute to indicate the up side?

### ISSUE THREAD

**Issue by middelink** [Koenkk/zigbee-shepherd-converters#641]
Currently, in when we received a "flip180", https://github.com/Koenkk/zigbee-shepherd-converters/blob/master/converters/fromZigbee.js#L553 puts the up face in the attribute "side", however when we receive a "flip90", it stores side which is now "up" in "to_side", both of which are stored in the state.json and so will be added to all next mqtt messages. At that point in time I have NO idea which is the side facing up, the one in "side" or in the "to_side" attribute? Who knows :)

This can be easily fixed by having the flip90 put the side facing up in "side" as well. However this will be a breaking change for people who rely on "to_side" being filled.
Do we care?

Happy to create the 1-line PR, but I would rather hash this out first.

**Comment by Koenkk** [comment]
I wonder if these properties should be cached at all, does adding `side`, `from_side` and `to_side` to https://github.com/Koenkk/zigbee2mqtt/blob/dev/lib/state.js#L10 fix your issue?

**Comment by middelink** [comment]
Hmm, I don't think so. Although, I can see the point of `from_side` and `to_side` being ephemeral. `side` however has meaning when for example you want to use the rotation to change brightness or volume. It is important to know which face is up, aka what lamp/speaker the user selected.

What about setting  `side`as well in the `flip90` struct which, as `side` would still be cached, will remove the confusion which face is up for rotation.

Uncaching `from_side` and `to_side` is definitely advisable as they are only valid during a `flip90`, but not required in the above solution :)

**Comment by Koenkk** [comment]
I agree that `side` has to be the actual side it is currently on and thus can be cached, can you make a PR?

**Comment by Koenkk** [comment]
merged, thanks!
