### ISSUE TITLE
(Finished) pull-request for GUNNARP (40x40 panel) support

### ISSUE THREAD

**Issue by insensitiveclod** [Koenkk/zigbee-shepherd-converters#659]
Hi

I bought a Gunnarp panel today.
I will be submitting a pull-request for the GUNNARP 40x40 panel some time soon; expect somewhere begin next week as I am tight on time this weekend.

This message is just to let people know that it's coming, and if they have some issues, they could add it to this ticket.

Note I do not have access to the round version of the lamp; it'd be good to see if there's someone who has it.

I will also endevour a pull-request for the zigbee2mqtt.io documentation soon after, supplying docs for how to get this lamp working.

Cheers.

**Comment by insensitiveclod** [comment]
Created pull-request.

**Comment by Koenkk** [comment]
Merged, thanks!
