### ISSUE TITLE
Question:  how are temperature and battery reports handled from contact sensors?

### ISSUE THREAD

**Issue by skandragon** [Koenkk/zigbee-shepherd-converters#673]
I don't see an example of this being done, and I'm not a Javascript expert by any means.

What I'd like to be able to do is get hourly (or so) reports pushed from devices, sort of as a "check in please" thing.  Many contact/door sensors -- all the ones I have anyway -- can report these periodically.  However, I don't see where this is set up to the end devices, although I do see handling of the reports should they arrive.

Is there support for requesting such from participating devices?

**Comment by Koenkk** [comment]
This can be set in the `configure` method but this requires manual changes. But if you want something like an availability feature for end devices please take a look at https://github.com/Koenkk/zigbee2mqtt/issues/775#issuecomment-496233849

**Comment by skandragon** [comment]
Thanks.  I'll move the discussion there; we are asking for the same thing, except I'm also wanting to add the configure step to specify the interval, or to enable it if it's not by default.
