### ISSUE TITLE
Add support for Philips Hue LCT016

### ISSUE THREAD

**Issue by srange** [Koenkk/zigbee-shepherd-converters#68]
There's a new model ID for the color A19 bulb.  According to the Philips forum, it's directly equivalent to the LCT014 with no API changes

[https://developers.meethue.com/content/model-lct016](https://developers.meethue.com/content/model-lct016)

I'm using the hassio component, so can't practically test this on my bulb, but I believe all that's needed is an addition to the zigbeeModel array of the 9290012573A entry in devices.js:490 , similar to #58  

I can't find any evidence online that there's a LWB016 to go along with the LCT.

**Comment by Koenkk** [comment]
Supported in the dev branch now, thanks!
