### ISSUE TITLE
Support for iluminize 511.201 LED dimmer

### ISSUE THREAD

**Issue by afurtenbacher** [Koenkk/zigbee-shepherd-converters#688]
Hi,
please support the iluminize LED dimmer 511.201. 
![511 201](https://user-images.githubusercontent.com/46393106/66807555-97251c00-ef29-11e9-87cf-2ddfc8687d4b.png)
Please let me know if I can help in any way. 
This adds the device, but the items are not being discovered:
{
        zigbeeModel: ['511.201'],
        model: '511.201',
        vendor: 'iluminize',
        description: 'iluminize HV LED dimmer',
        extend: generic.light_onoff_brightness,
    },
I get 
"511.201" not described in statesMapping.
in the logs

Thx

**Comment by Koenkk** [comment]
Added, ready to be integrated in iobroker now.
