### ISSUE TITLE
Device with modelID 'LOM002' is not supported (Philips Hue Smart Plug)

### ISSUE THREAD

**Issue by 0neV1s10n** [Koenkk/zigbee-shepherd-converters#691]
Hey,

Trying to pair this device:
https://www2.meethue.com/en-us/p/hue-smart-plug/046677552343

I get following error in logs:
zigbee2mqtt:warn 10/15/2019, 4:52:58 PM Device with modelID 'LOM002' is not supported.
  zigbee2mqtt:warn 10/15/2019, 4:52:58 PM Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

I'm running on Hassio and the resolution path described in the above page doesn't help. I can't find any shepherd directory.

Can you help with this ?

Many thanks for your work anyway.

JimmyK

**Comment by allofmex** [comment]
Please search for file devices.js

LOM001 is already supported and LOM002 should work the same way. It should be enough to add ,'LOM002' in line https://github.com/Koenkk/zigbee-shepherd-converters/blob/8f82cbff612d74b9684b41e980f45d4631f600cc/devices.js#L1186

**Comment by 0neV1s10n** [comment]
> Please search for file devices.js
> 
> LOM001 is already supported and LOM002 should work the same way. It should be enough to add ,'LOM002' in line
> 
> https://github.com/Koenkk/zigbee-shepherd-converters/blob/8f82cbff612d74b9684b41e980f45d4631f600cc/devices.js#L1186

Thanks.

All I had to do is:

- create a device.js in /share/zigbee2mqtt
- pull / copy the [device.js](https://github.com/Koenkk/zigbee-shepherd-converters/blob/8f82cbff612d74b9684b41e980f45d4631f600cc/devices.js#L1186) content, replace LOM001 by LOM002
- add a section in zigbee2mqtt configuration.yaml:
"zigbee_shepherd_devices": true
- restart zigbee2mqtt add-on

Now, it seems my device is paired, but I can't see it in the hassio device list.

Here are few logs:

`2019-10-15.23-46-10/log.txt:76:10/15/2019, 11:46:53 PM - debug: Allowing device '0x0017880108050b2a' to join
2019-10-15.23-46-10/log.txt:77:10/15/2019, 11:46:53 PM - debug: Received zigbee message of type 'devIncoming' with data '"0x0017880108050b2a"' of device 'LOM002' (0x0017880108050b2a) of endpoint 11
2019-10-15.23-46-10/log.txt:80:10/15/2019, 11:46:53 PM - debug: Received zigbee message of type 'devStatus' with data '"online"' of device 'LOM002' (0x0017880108050b2a) of endpoint 11
2019-10-15.23-46-10/log.txt:83:10/15/2019, 11:47:04 PM - debug: Configuring 0x0017880108050b2a (0x0017880108050b2a) ...
2019-10-15.23-46-10/log.txt:84:10/15/2019, 11:47:05 PM - info: Successfully configured 0x0017880108050b2a (0x0017880108050b2a)`


Any idea why this is happening ?

Thanks again.

**Comment by 0neV1s10n** [comment]
> Please search for file devices.js
> 
> LOM001 is already supported and LOM002 should work the same way. It should be enough to add ,'LOM002' in line
> 
> https://github.com/Koenkk/zigbee-shepherd-converters/blob/8f82cbff612d74b9684b41e980f45d4631f600cc/devices.js#L1186

Hi,
I figured it out.
LOM002 is closer to zigbeeModel: ['Plug 01'], hence I took that one as an example, and it works all fine.
Thanks for your support ;-)

**Comment by allofmex** [comment]
They are almost the same, you are right. For basic functionality, line fromZigbee and toZigbee are important. And they are same for both.
```
       zigbeeModel: ['Plug 01'],
        ...
        supports: 'on/off',
       ....
        fromZigbee: [fz.ignore_onoff_change, fz.state],
        toZigbee: [tz.on_off],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 3);
        ....
```

 ```
   {
        zigbeeModel: ['LOM001'],
        ...
        description: 'Hue smart plug',
        supports: 'on/off',
        fromZigbee: [fz.ignore_onoff_change, fz.state],
        toZigbee: [tz.on_off],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 11);
        ....
    },
```
So it must work with LOM001 entry too.
May you please test again, then we can implement it for others too.
Please revert Osram section and change line
`zigbeeModel: ['LOM001'],` to `       zigbeeModel: ['LOM001', 'LOM002'],`. 

Configure part is different, and according to your log, endpoint 11 will be correct, but Osram has 3, so this part will not work if you use osrams.

Note: after editing you must restart your broker to activate changes.

**Comment by 0neV1s10n** [comment]
Hey, I re-tested it, and I confirm it works by only changing this line to original file:
`zigbeeModel: ['LOM001'], to zigbeeModel: ['LOM001', 'LOM002'],.`

Thanks.

**Comment by Koenkk** [comment]
Added support for, will be available in the dev branch within a few hours.
