### ISSUE TITLE
Support for Sylvania 74696 Bulb

### ISSUE THREAD

**Issue by pfischbach** [Koenkk/zigbee-shepherd-converters#82]
Can you please add support for this bulb Sylvania 74696.
I will try to contribute in the future but need to get up to speed with GIT first.

{

        zigbeeModel: ['A19 W 10 year'],

        model: '74696',

        vendor: 'Sylvania',

        description: 'SMART+ LED soft white dimmable A19',

        supports: generic.light_onoff_brightness().supports,

        fromZigbee: generic.light_onoff_brightness().fromZigbee,

        toZigbee: generic.light_onoff_brightness().toZigbee,

    },

**Comment by Koenkk** [comment]
Done, thanks!
