### ISSUE TITLE
Osram lamp "is not supported" after upgrading zigbee2mqtt

### ISSUE THREAD

**Issue by noahf1** [Koenkk/zigbee-shepherd-converters#85]
Today I got a new Osram lamp (OSRAM SMART+ CLASSIC A 60 TW) and I upgraded my zigbee2mqtt version from 1.2 to 1.6 to because it was not supported in this version. After upgrading the version, my old Osram lamp (OSRAM LIGHTIFY LED CLA60 E27 RGBW) is now an unsupported device and it does not work anymore.

I am using the zigbee2mqtt version for docker.

Logs: https://pastebin.com/S6ZzBJkX

Error: `  zigbee2mqtt:warn 2018-9-27 20:31:48 Device with modelID '0x4d4152534f2057424752203036414c43' is not supported.`

Any ideas? do you need more information?

edit: 0x4d4152534f2057424752203036414c43 means "MARSO WBGR 06ALC" in ascii (reverse order)

Seems to be the same issue: #https://github.com/Koenkk/zigbee2mqtt/issues/388

edit2: got it fixed with rolling back to zigbee2mqtt version 0.1.3, has nothing to do with the shepherd converters.

Regards
Noah

**Comment by Koenkk** [comment]
As you mentioned, this is indeed the same issue as in: https://github.com/Koenkk/zigbee2mqtt/issues/388. Let's continue there.
