### ISSUE TITLE
Improvement converter configuration

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee-shepherd-converters#90]
hi @Koenkk 
we need some sort of replay action for failed converter configuration in single-steps.
sometimes it could be failed to do some bind or do write command on ias devices so we need to do it again to get them hopefully working.
instead insert every cb command as second ones in codeblock we should do it automatic.
if one cb give error message from any type we should do it minimally ones again, maybe so some of configurable variable could be help.

**Comment by Koenkk** [comment]
that's an good idea! 

Did you experience this issue? (So that it worked correctly after doing the same configuration again)

**Comment by tb-killa** [comment]
Yes, sadly on most Devices who are on Power standby by pairing. Some ssIasZone Devices too.

**Comment by tb-killa** [comment]
@Koenkk Do you actually working on this ?
I´m thinking this would help a lot of open issues by failed configured devices ..

**Comment by Koenkk** [comment]
@tb-killa Yes, will do it together when I move the device configure code out of `controller.js` and move it to an extension.
